import type { DocsExample } from '@/docs/components/page-definition'; import { controlledStringApplication, foldkitApplication } from '@/docs/components/pages/authored-page';
export const fieldFixtures = [{ title: 'Anatomy', description: 'Keep the label, controlled input, and supporting text together without moving input state into Field.' }, { title: 'Validation error', description: 'Render an alert only when the parent validation result says the field is invalid.' }, { title: 'Async validation', description: 'Version each validation Command and ignore stale responses so slower results cannot overwrite the latest parent-owned value.' }, { title: 'Field group', description: 'Group related fields under one spacing contract while each input keeps a unique id.' }] as const;
const imports = (renderer: 'tailwind' | 'stylex') => `import * as Input from '@/${renderer === 'stylex' ? 'stylex' : 'ui'}/input'${renderer === 'stylex' ? "\nimport * as stylex from '@stylexjs/stylex'\n\nconst styles = stylex.create({ field: { maxWidth: '24rem' } })" : ''}`;
const layout = (renderer: 'tailwind' | 'stylex') => renderer === 'stylex' ? 'layoutStyle: styles.field' : "class: 'max-w-sm'";
const controlled = (index: 0 | 1 | 3, renderer: 'tailwind' | 'stylex'): string => controlledStringApplication({ componentName: 'Field', componentSlug: 'field', renderer, exampleName: fieldFixtures[index].title, field: 'name', initialValue: '', messageName: 'ChangedName', componentImports: imports(renderer), viewBody: index === 3 ? `Field.fieldGroup({ ${layout(renderer)}, children: [
  Field.controlField({ id: 'first-name', label: 'First name', toControl: (parts, controlH) => Input.input({ id: parts.controlId, value: model.name, onInput: value => ChangedName({ value }) }, controlH) }, h),
  Field.controlField({ id: 'last-name', label: 'Last name', toControl: (parts, controlH) => Input.input({ id: parts.controlId, value: model.name, onInput: value => ChangedName({ value }) }, controlH) }, h),
] }, h),` : `Field.controlField({ id: 'display-name', label: 'Display name', ${index === 0 ? "description: 'Shown on your public profile.'," : "error: 'Display name is required.',"} ${layout(renderer)}, toControl: (parts, controlH) => Input.input({ id: parts.controlId, value: model.name, onInput: value => ChangedName({ value }),${index === 0 ? " placeholder: 'Ada Lovelace'," : ''} ...(parts.describedBy === undefined ? {} : { describedBy: parts.describedBy }), isInvalid: parts.isInvalid, isDisabled: parts.isDisabled }, controlH) }, h),` });
const asyncSource = (renderer: 'tailwind' | 'stylex'): string => foldkitApplication({ title: 'Field — Async validation', imports: `import { Effect, Schema as S } from 'effect'\nimport { Command, Runtime, Subscription } from 'foldkit'\nimport { type Document, type HtmlBuilder } from 'foldkit/html'\nimport { m } from 'foldkit/message'\n\nimport * as Field from '@/${renderer === 'stylex' ? 'stylex' : 'ui'}/field'\n${imports(renderer)}`, model: `export const Model = S.Struct({ username: S.String, validationVersion: S.Number, error: S.NullOr(S.String) })\nexport type Model = typeof Model.Type`, messages: `export const ChangedUsername = m('ChangedUsername', { value: S.String })\nexport const CompletedUsernameValidation = m('CompletedUsernameValidation', { version: S.Number, error: S.NullOr(S.String) })\nexport const Message = S.Union([ChangedUsername, CompletedUsernameValidation])\nexport type Message = typeof Message.Type`, init: `export const init = (): readonly [Model, ReadonlyArray<Command.Command<Message>>] => [{ username: '', validationVersion: 0, error: null }, []]`, update: `const ValidateUsername = Command.define('ValidateUsername', { args: { username: S.String, version: S.Number }, messages: [CompletedUsernameValidation], execute: ({ username, version }) => Effect.sleep('250 millis').pipe(Effect.as(CompletedUsernameValidation({ version, error: username.length < 3 ? 'Use at least three characters.' : null }))) })
export const update = (model: Model, message: Message): readonly [Model, ReadonlyArray<Command.Command<Message>>] => { switch (message._tag) { case 'ChangedUsername': { const validationVersion = model.validationVersion + 1; return [{ ...model, username: message.value, validationVersion, error: null }, [ValidateUsername({ username: message.value, version: validationVersion })]] } case 'CompletedUsernameValidation': return message.version === model.validationVersion ? [{ ...model, error: message.error }, []] : [model, []] } }`, view: `export const view = (model: Model, h: HtmlBuilder<Message>): Document => ({ title: 'Field — Async validation', body: Field.controlField({ id: 'username', label: 'Username', description: 'Availability is checked after each edit.', ...(model.error === null ? {} : { error: model.error }), ${layout(renderer)}, toControl: (parts, controlH) => Input.input({ id: parts.controlId, value: model.username, onInput: value => ChangedUsername({ value }), ...(parts.describedBy === undefined ? {} : { describedBy: parts.describedBy }), isInvalid: parts.isInvalid, isDisabled: parts.isDisabled }, controlH) }, h) })` });
export const fieldExamples = (renderer: 'tailwind' | 'stylex'): ReadonlyArray<DocsExample> => fieldFixtures.map((fixture, index) => ({ ...fixture, code: index === 2 ? asyncSource(renderer) : controlled(index as 0 | 1 | 3, renderer) }));
