import type { DocsExample } from '@/docs/components/page-definition';
import { foldkitApplication } from '@/docs/components/pages/authored-page';
export const resizableFixtures = [
  { title: 'Editor and preview', description: 'Pointer and keyboard events update one explicit split percentage.', direction: 'horizontal', initialSize: 50, extent: 640, ariaLabel: 'Resize editor and preview', first: 'Editor', second: 'Preview' },
  { title: 'Vertical split', description: 'A second panel group needs a separate Model and message route even when it lives on the same page.', direction: 'vertical', initialSize: 40, extent: 256, ariaLabel: 'Resize workspace rows', first: 'Canvas', second: 'Console' },
] as const;
const source = (fixture: (typeof resizableFixtures)[number], renderer: 'tailwind' | 'stylex'): string => { const isStyleX = renderer === 'stylex'; const tag = fixture.title.replaceAll(/[^a-zA-Z0-9]/g, ''); return foldkitApplication({
  title: `Resizable — ${fixture.title}`,
  imports: `import { Schema as S } from 'effect'\nimport { Command, Runtime, Subscription } from 'foldkit'\nimport { type Document, type HtmlBuilder } from 'foldkit/html'\nimport { m } from 'foldkit/message'\n${isStyleX ? "import * as stylex from '@stylexjs/stylex'\n" : ''}\nimport * as Resizable from '@/${isStyleX ? 'stylex' : 'ui'}/resizable'`,
  model: `${isStyleX ? "const styles = stylex.create({ group: { height: '16rem', width: '100%', maxWidth: '40rem' }, panel: { alignItems: 'center', display: 'flex', justifyContent: 'center', padding: '1rem', height: '100%', width: '100%' } })\n" : ''}export const Model = S.Struct({ panels: Resizable.Model })\nexport type Model = typeof Model.Type`,
  messages: `export const GotResizableMessage = m('GotResizableMessage${tag}', { message: Resizable.Message })\nexport const Message = S.Union([GotResizableMessage])\nexport type Message = typeof Message.Type`,
  init: `export const init = (): readonly [Model, ReadonlyArray<Command.Command<Message>>] => [\n  { panels: Resizable.init('workspace-panels', ${fixture.initialSize}) },\n  [],\n]`,
  update: `export const update = (model: Model, message: Message): readonly [Model, ReadonlyArray<Command.Command<Message>>] => {\n  switch (message._tag) {\n    case 'GotResizableMessage${tag}': return [{ ...model, panels: Resizable.update(model.panels, message.message) }, []]\n  }\n}`,
  view: `export const view = (model: Model, h: HtmlBuilder<Message>): Document => ({\n  title: 'Resizable — ${fixture.title}',\n  body: h.main([h.Class('mx-auto max-w-2xl p-8')], [\n    Resizable.resizable({\n      model: model.panels, toParentMessage: message => GotResizableMessage({ message }),\n      direction: '${fixture.direction}', extent: ${fixture.extent}, withHandle: true, ariaLabel: '${fixture.ariaLabel}',\n      ${isStyleX ? 'layoutStyle: styles.group' : "class: 'h-64 w-full'"},\n      first: h.div([h.Class(${isStyleX ? "stylex.props(styles.panel).className ?? ''" : "'flex size-full items-center justify-center p-4'"})], ['${fixture.first}']),\n      second: h.div([h.Class(${isStyleX ? "stylex.props(styles.panel).className ?? ''" : "'flex size-full items-center justify-center p-4'"})], ['${fixture.second}']),\n    }, h),\n  ]),\n})`,
}); };
export const resizableExamples = (renderer: 'tailwind' | 'stylex'): ReadonlyArray<DocsExample> => resizableFixtures.map(fixture => ({ title: fixture.title, description: fixture.description, code: source(fixture, renderer) }));
