import * as stylex from '@stylexjs/stylex'

import { complexTokens } from '../complex-tokens.stylex'
import { foundationTokens } from '../foundations-tokens.stylex'
import { interactionTokens } from '../interaction-tokens.stylex.const'
import { tokens } from '../tokens.stylex'

export const styles = stylex.create({
  cell: {
    paddingBlock: '0.75rem',
    paddingInline: '0.75rem',
    verticalAlign: 'middle',
    whiteSpace: 'nowrap',
  },
  cellCompact: { paddingBlock: '0.375rem' },
  checkboxBox: {
    borderColor: tokens.input,
    borderRadius: foundationTokens.checkboxRadius,
    borderStyle: 'solid',
    borderWidth: 1,
    placeContent: 'center',
    backgroundColor: tokens.background,
    color: tokens.primaryForeground,
    display: 'grid',
    height: '1rem',
    width: '1rem',
  },
  checkboxBoxChecked: { borderColor: tokens.primary, backgroundColor: tokens.primary },
  checkboxButton: {
    padding: 0,
    borderWidth: 0,
    placeContent: 'center',
    backgroundColor: tokens.transparent,
    cursor: interactionTokens.cursorAction,
    display: 'grid',
    height: '2.5rem',
    width: '2.5rem',
  },
  chooser: { position: 'relative' },
  chooserPanel: {
    padding: '0.5rem',
    borderColor: tokens.border,
    borderRadius: tokens.controlRadius,
    borderStyle: 'solid',
    borderWidth: 1,
    gap: '0.125rem',
    backgroundColor: tokens.card,
    boxShadow: tokens.shadowCard,
    display: 'grid',
    position: 'absolute',
    zIndex: 30,
    minWidth: '15rem',
    right: 0,
    top: 'calc(100% + 0.375rem)',
  },
  chooserSummary: {
    borderColor: tokens.border,
    borderRadius: tokens.controlRadius,
    borderStyle: 'solid',
    borderWidth: 1,
    listStyle: 'none',
    paddingInline: '0.75rem',
    alignItems: 'center',
    backgroundColor: { default: tokens.background, ':hover': complexTokens.mutedSurface },
    cursor: interactionTokens.cursorAction,
    display: 'flex',
    fontSize: '0.875rem',
    fontWeight: 500,
    height: '2.5rem',
  },
  empty: { color: tokens.mutedForeground, textAlign: 'center', height: '8rem' },
  filter: {
    borderColor: { default: tokens.input, ':focus-visible': tokens.ring },
    borderRadius: tokens.controlRadius,
    borderStyle: 'solid',
    borderWidth: 1,
    paddingInline: '0.75rem',
    backgroundColor: tokens.background,
    boxShadow: { default: tokens.shadowSm, ':focus-visible': tokens.focusRingShadow },
    color: tokens.foreground,
    fontFamily: 'inherit',
    fontSize: '0.875rem',
    outlineStyle: 'none',
    height: '2.5rem',
    maxWidth: '25rem',
    width: '100%',
  },
  head: {
    paddingInline: '0.75rem',
    color: tokens.mutedForeground,
    fontSize: '0.75rem',
    fontWeight: 600,
    letterSpacing: '0.025em',
    textAlign: 'left',
    textTransform: 'uppercase',
    verticalAlign: 'middle',
    whiteSpace: 'nowrap',
    height: '2.75rem',
  },
  header: { backgroundColor: complexTokens.mutedSurface },
  metric: { fontVariantNumeric: 'tabular-nums' },
  option: {
    gap: '0.5rem',
    alignItems: 'center',
    display: 'flex',
    fontSize: '0.875rem',
    minHeight: '2.5rem',
  },
  pinned: {
    backgroundColor: tokens.card,
    boxShadow: tokens.shadowCard,
    position: 'sticky',
    zIndex: 4,
  },
  pinnedRow: { backgroundColor: complexTokens.mutedSurface },
  range: { accentColor: tokens.primary, minWidth: '10rem' },
  row: {
    backgroundColor: { default: tokens.transparent, ':hover': complexTokens.mutedSurface },
    transitionDuration: interactionTokens.motionFast,
    transitionProperty: 'background-color',
    borderBottomColor: tokens.border,
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
  },
  rowSelected: { backgroundColor: complexTokens.mutedSurface },
  select: {
    borderColor: tokens.border,
    borderRadius: tokens.controlRadius,
    borderStyle: 'solid',
    borderWidth: 1,
    paddingInline: '0.625rem',
    backgroundColor: tokens.background,
    color: tokens.foreground,
    fontFamily: 'inherit',
    fontSize: '0.875rem',
    height: '2.5rem',
  },
  sortButton: {
    font: 'inherit',
    padding: '0.25rem',
    borderRadius: tokens.controlRadius,
    gap: '0.25rem',
    alignItems: 'center',
    backgroundColor: tokens.transparent,
    color: 'inherit',
    cursor: interactionTokens.cursorAction,
    display: 'inline-flex',
    minHeight: '2.5rem',
  },
  table: { borderCollapse: 'separate', borderSpacing: 0, fontSize: '0.875rem', minWidth: '68rem', width: '100%' },
  tableShell: {
    borderColor: tokens.border,
    borderRadius: tokens.controlRadius,
    borderStyle: 'solid',
    borderWidth: 1,
    overflowX: 'auto',
  },
})
