import * as stylex from '@stylexjs/stylex'

import { complexTokens } from '../complex-tokens.stylex'
import { interactionTokens } from '../interaction-tokens.stylex.const'
import { tokens } from '../tokens.stylex'

const spin = stylex.keyframes({ to: { transform: 'rotate(360deg)' } })

export const styles = stylex.create({
  root: { display: 'flex', position: 'relative', height: '100%', minWidth: 0, width: '100%', },
  resizing: { cursor: interactionTokens.cursorResizeHorizontal, userSelect: 'none' },
  tableColumn: { display: 'flex',
 flexBasis: '0%',
 flexDirection: 'column',
 flexGrow: '1',
 flexShrink: '1',
 minWidth: 0, },
  tableFrame: { borderColor: tokens.border,
 borderRadius: tokens.radius,
 borderStyle: 'solid',
 borderWidth: 1,
 overflow: 'hidden',
 backgroundColor: tokens.background,
 display: 'flex',
 flexBasis: '0%',
 flexGrow: '1',
 flexShrink: '1',
 position: 'relative',
 minHeight: '12rem',
 minWidth: 0, },
  tableFrameModified: { borderBottomLeftRadius: 0, borderTopLeftRadius: 0 },
  scroller: { overflow: 'auto',
 flexBasis: '0%',
 flexGrow: '1',
 flexShrink: '1',
 position: 'relative',
 minWidth: 0, },
  grid: { paddingInline: '1rem', display: 'grid', minWidth: '100%', width: 'max-content', },
  header: { backgroundColor: complexTokens.mutedSurface, position: 'sticky', zIndex: 20, borderBottomColor: tokens.border, borderBottomStyle: 'solid', borderBottomWidth: 1, minHeight: '2.75rem', top: 0, },
  headerCell: { alignSelf: 'stretch', position: 'relative', minWidth: 0, },
  headerInner: { gap: '0.25rem', overflow: 'visible', alignItems: 'center', display: 'flex', paddingInlineEnd: '0.625rem', height: '100%', minWidth: 0, },
  prefixCell: { alignItems: 'center', alignSelf: 'stretch', display: 'flex', justifyContent: 'center', minWidth: 0 },
  cellInset: { paddingInlineStart: '1rem' },
  sortButton: { padding: 0,
 borderWidth: 0,
 gap: '0.375rem',
 alignItems: 'center',
 backgroundColor: tokens.transparent,
 color: { default: tokens.mutedForeground, ':hover': tokens.foreground },
 cursor: interactionTokens.cursorAction,
 display: 'flex',
 flexBasis: '0%',
 flexGrow: '1',
 flexShrink: '1',
 fontFamily: 'inherit',
 fontSize: '0.875rem',
 fontWeight: 500,
 textAlign: 'left',
 transitionDuration: interactionTokens.motionFast,
 transitionProperty: 'color',
 minHeight: '2.5rem',
 minWidth: 0, },
  sortIcon: { color: tokens.primary, flexShrink: 0, height: '0.75rem', width: '0.75rem' },
  sortIconIdle: { color: tokens.mutedForeground, opacity: 0.3 },
  info: { alignItems: 'center', color: tokens.primary, cursor: interactionTokens.cursorDefault, display: 'inline-flex', flexShrink: 0, opacity: 0.8 },
  truncate: { overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', minWidth: 0, },
  rows: { minWidth: '100%', width: 'max-content' },
  row: { alignItems: 'center', fontSize: '0.875rem', transitionDuration: interactionTokens.motionFast, transitionProperty: 'background-color', borderBottomColor: tokens.border, borderBottomStyle: 'solid', borderBottomWidth: 1, minHeight: '3rem', },
  rowInteractive: { backgroundColor: { default: tokens.transparent, ':hover': complexTokens.mutedSurface }, cursor: interactionTokens.cursorAction },
  rowSelected: { backgroundColor: complexTokens.accentSurface },
  rowExpanded: { backgroundColor: complexTokens.mutedSurface },
  bodyCell: { overflow: 'hidden', alignItems: 'center', alignSelf: 'stretch', display: 'flex', whiteSpace: 'nowrap', minWidth: 0, },
  stickyHeader: { backgroundColor: complexTokens.opaqueMutedSurface, isolation: 'isolate', position: 'sticky', zIndex: 50 },
  stickyBody: { backgroundColor: tokens.background, isolation: 'isolate', position: 'sticky', transitionDuration: interactionTokens.motionFast, transitionProperty: 'background-color', zIndex: 10 },
  stickyPrefixHeader: { zIndex: 55 },
  stickyPrefixBody: { zIndex: 20 },
  stickyLeading: { boxSizing: 'border-box', paddingInlineStart: '1rem', transform: 'translateX(-1rem)', width: 'calc(100% + 1rem)' },
  stickySelected: { backgroundColor: complexTokens.opaqueAccentSurface },
  stickyExpanded: { backgroundColor: complexTokens.opaqueMutedSurface },
  checkbox: { padding: 0, borderColor: tokens.mutedForeground, borderRadius: complexTokens.smallRadius, borderStyle: 'solid', borderWidth: 2, alignItems: 'center', backgroundColor: tokens.transparent, color: tokens.primaryForeground, cursor: interactionTokens.cursorAction, display: 'inline-flex', justifyContent: 'center', transitionDuration: interactionTokens.motionFast, transitionProperty: 'background-color, border-color', height: '1rem', width: '1rem', },
  checkboxChecked: { borderColor: tokens.primary, backgroundColor: tokens.primary, },
  checkboxIcon: { height: '0.75rem', width: '0.75rem' },
  expandIcon: { color: tokens.mutedForeground, transitionDuration: interactionTokens.motionModerate, transitionProperty: 'transform', height: '1rem', width: '1rem', },
  expandIconOpen: { transform: 'rotate(180deg)' },
  expandedContent: { padding: '1rem', backgroundColor: complexTokens.mutedSurface, borderBottomColor: tokens.border, borderBottomStyle: 'solid', borderBottomWidth: 1, },
  resizeHandle: { alignItems: 'center', backgroundColor: { default: complexTokens.mutedSurface, ':hover': tokens.border }, cursor: interactionTokens.cursorResizeHorizontal, display: 'flex', justifyContent: 'center', position: 'absolute', transitionDuration: interactionTokens.motionModerate, transitionProperty: 'background-color', zIndex: 35, bottom: 0, right: '-0.25rem', top: 0, width: '0.5rem', },
  resizeDots: { opacity: 0.65, borderLeftColor: tokens.mutedForeground, borderLeftStyle: 'dotted', borderLeftWidth: 1, height: '1.25rem', width: 1, },
  filterControl: { flexShrink: 0, position: 'relative', zIndex: 0 },
  filterTrigger: { padding: '0.125rem', borderRadius: complexTokens.smallRadius, borderWidth: 0, alignItems: 'center', backgroundColor: tokens.transparent, color: tokens.mutedForeground, cursor: interactionTokens.cursorAction, display: 'inline-flex', justifyContent: 'center', opacity: { default: 0, ':hover': 1 }, transitionDuration: interactionTokens.motionFast, transitionProperty: 'opacity, background-color, color', height: '1.5rem', width: '1.5rem', },
  filterTriggerActive: { backgroundColor: complexTokens.accentSurface, color: tokens.primary, opacity: 1 },
  filterIcon: { height: '0.75rem', width: '0.75rem' },
  filterPanel: { padding: '0.75rem', borderColor: tokens.border, borderRadius: tokens.radius, borderStyle: 'solid', borderWidth: 1, gap: '0.5rem', backgroundColor: tokens.card, boxShadow: tokens.shadowCard, color: tokens.foreground, display: 'flex', flexDirection: 'column', position: 'fixed', zIndex: 60, maxHeight: 'min(40rem, calc(100vh - 1rem))', top: 'calc(anchor(bottom) + 0.25rem)', },
  textFilterPanel: { left: 'max(0.5rem, calc(anchor(right) - 13.75rem))', minWidth: '13.75rem' },
  enumFilterPanel: { overflow: 'hidden', left: 'max(0.5rem, calc(anchor(right) - 13.75rem))', minWidth: '13.75rem', },
  numberFilterPanel: { overflow: 'visible', left: 'max(0.5rem, calc(anchor(right) - 17.5rem))', minWidth: '17.5rem', },
  dateFilterPanel: { left: 'max(0.5rem, calc(anchor(right) - 40rem))', minWidth: '40rem' },
  filterInput: { borderColor: tokens.border, borderRadius: tokens.controlRadius, borderStyle: 'solid', borderWidth: 1, paddingInline: '0.5rem', backgroundColor: tokens.background, color: tokens.foreground, fontFamily: 'inherit', fontSize: '0.8125rem', outlineColor: { default: tokens.transparent, ':focus-visible': tokens.ring }, outlineStyle: 'solid', outlineWidth: 1, height: '2rem', width: '100%', },
  filterActions: { gap: '0.25rem', display: 'flex', },
  filterApply: { flexBasis: '0%', flexGrow: 1, flexShrink: 1 },
  panelHeading: { alignItems: 'center', color: tokens.mutedForeground, display: 'flex', fontSize: '0.75rem', justifyContent: 'space-between' },
  resetText: { padding: 0, borderWidth: 0, backgroundColor: tokens.transparent, color: tokens.destructive, cursor: interactionTokens.cursorAction, fontFamily: 'inherit', fontSize: '0.75rem', },
  enumOptions: { overflow: 'auto', display: 'flex', flexDirection: 'column', maxHeight: '13rem', },
  enumOption: { borderRadius: tokens.controlRadius, gap: '0.5rem', paddingInline: '0.5rem', alignItems: 'center', cursor: interactionTokens.cursorAction, display: 'flex', minHeight: '2rem', },
  enumLabel: { flexBasis: '0%',
 flexGrow: '1',
 flexShrink: '1',
 fontSize: '0.875rem', },
  optionCount: { color: tokens.mutedForeground, fontSize: '0.75rem', fontVariantNumeric: 'tabular-nums' },
  field: { gap: '0.375rem', color: tokens.mutedForeground, display: 'flex', flexDirection: 'column', fontSize: '0.75rem', },
  select: { borderColor: tokens.border, borderRadius: tokens.controlRadius, borderStyle: 'solid', borderWidth: 1, paddingInline: '0.5rem', backgroundColor: tokens.background, color: tokens.foreground, fontFamily: 'inherit', height: '2.25rem', width: '100%', },
  twoFields: { gap: '0.5rem', display: 'grid', gridTemplateColumns: '1fr 1fr', },
  inputWithUnit: { borderColor: tokens.border, borderRadius: tokens.controlRadius, borderStyle: 'solid', borderWidth: 1, overflow: 'hidden', alignItems: 'center', display: 'flex', paddingInlineEnd: '0.5rem', },
  errorText: { margin: 0, color: tokens.destructive, fontSize: '0.75rem', },
  panelFooter: { alignItems: 'center', display: 'flex', justifyContent: 'space-between' },
  datePresetPanel: { padding: '0.25rem', left: 'max(0.5rem, calc(anchor(right) - 15rem))', minWidth: '15rem', },
  datePresetList: { display: 'flex', flexDirection: 'column' },
  datePresetButton: { borderRadius: tokens.controlRadius, borderWidth: 0, gap: '0.5rem', paddingInline: '0.75rem', alignItems: 'center', backgroundColor: { default: tokens.transparent, ':hover': tokens.accent }, color: tokens.foreground, cursor: interactionTokens.cursorAction, display: 'flex', fontFamily: 'inherit', fontSize: '0.875rem', fontWeight: 500, justifyContent: 'flex-start', height: '2rem', width: '100%' },
  separator: { marginBlock: '0.25rem', backgroundColor: tokens.border, height: '1px', width: '100%' },
  dateCustomHeading: { alignItems: 'center', display: 'flex', justifyContent: 'space-between' },
  dateFields: { gap: '0.75rem', display: 'grid', gridTemplateColumns: '1fr 1fr', },
  calendarMonths: { gap: '1rem', display: 'grid', gridTemplateColumns: '1fr 1fr' },
  calendarMonth: { gap: '0.5rem', display: 'flex', flexDirection: 'column' },
  calendarTitleRow: { alignItems: 'center', display: 'grid', gridTemplateColumns: '1.75rem 1fr 1.75rem' },
  calendarTitle: { fontSize: '0.8125rem', textAlign: 'center', textTransform: 'capitalize' },
  calendarNavigation: { padding: 0, borderRadius: tokens.controlRadius, borderWidth: 0, alignItems: 'center', backgroundColor: { default: tokens.transparent, ':hover': complexTokens.mutedSurface }, color: tokens.foreground, cursor: interactionTokens.cursorAction, display: 'inline-flex', justifyContent: 'center', height: '1.75rem', width: '1.75rem' },
  calendarNavigationSpacer: { height: '1.75rem', width: '1.75rem' },
  calendarGrid: { gap: '0.125rem', display: 'grid', gridTemplateColumns: 'repeat(7, 1fr)' },
  calendarWeekday: { color: tokens.mutedForeground, fontSize: '0.6875rem', textAlign: 'center' },
  calendarDay: { padding: 0, borderRadius: tokens.controlRadius, borderWidth: 0, backgroundColor: { default: tokens.transparent, ':hover': complexTokens.mutedSurface }, color: tokens.foreground, cursor: interactionTokens.cursorAction, fontFamily: 'inherit', fontSize: '0.75rem', height: '1.75rem', width: '1.75rem' },
  calendarDayRange: { backgroundColor: complexTokens.accentSurface },
  calendarDaySelected: { backgroundColor: tokens.primary, color: tokens.primaryForeground, fontWeight: 600 },
  calendarDayDisabled: { color: tokens.mutedForeground, cursor: interactionTokens.cursorDisabled, opacity: 0.35 },
  footer: { gap: { default: 0, '@media (max-width: 40rem)': '0.5rem' }, paddingInline: '0.5rem', alignItems: 'center', display: 'flex', flexWrap: { default: 'nowrap', '@media (max-width: 40rem)': 'wrap' }, justifyContent: 'space-between', paddingBlockEnd: '0.25rem', paddingBlockStart: '0.75rem', borderTopColor: tokens.border, borderTopStyle: 'solid', borderTopWidth: 1, },
  footerLeft: { gap: '0.75rem', alignItems: 'center', display: 'flex', flexWrap: 'wrap', width: { default: 'auto', '@media (max-width: 40rem)': '100%' }, },
  footerRight: { gap: '0.5rem', alignItems: 'center', display: 'flex', flexWrap: { default: 'nowrap', '@media (max-width: 40rem)': 'wrap' }, justifyContent: 'flex-end', minWidth: 0, width: { default: 'auto', '@media (max-width: 40rem)': '100%' }, },
  footerText: { color: tokens.mutedForeground, fontSize: '0.75rem', fontVariantNumeric: 'tabular-nums' },
  layoutWrap: { position: 'relative', zIndex: 45 },
  layoutPanel: { borderColor: tokens.border, borderRadius: tokens.radius, borderStyle: 'solid', borderWidth: 1, backgroundColor: tokens.card, boxShadow: tokens.shadowCard, position: 'absolute', zIndex: 60, bottom: 'calc(100% + 0.5rem)', right: 0, width: '20rem', },
  layoutHeader: { padding: '0.75rem', alignItems: 'center', display: 'flex', fontSize: '0.875rem', justifyContent: 'space-between', borderBottomColor: tokens.border, borderBottomStyle: 'solid', borderBottomWidth: 1, },
  layoutList: { padding: '0.5rem', overflow: 'auto', maxHeight: '26.25rem', },
  layoutItem: { borderRadius: tokens.controlRadius, gap: '0.125rem', paddingInline: '0.5rem', alignItems: 'center', display: 'flex', minHeight: '2.5rem', },
  layoutItemMuted: { color: tokens.mutedForeground },
  visibilityButton: { padding: 0,
 borderWidth: 0,
 gap: '0.5rem',
 alignItems: 'center',
 backgroundColor: tokens.transparent,
 color: 'inherit',
 cursor: interactionTokens.cursorAction,
 display: 'flex',
 flexBasis: '0%',
 flexGrow: '1',
 flexShrink: '1',
 fontFamily: 'inherit',
 textAlign: 'left',
 minWidth: 0, },
  modifiedToolbar: { padding: '0.5rem', borderColor: tokens.border, borderStyle: 'solid', gap: '0.75rem', alignItems: 'center', backgroundColor: complexTokens.mutedSurface, display: 'flex', flexDirection: 'column', borderBottomLeftRadius: tokens.radius, borderRightWidth: 1, borderTopLeftRadius: tokens.radius, },
  toolbarButton: { padding: 0, borderRadius: tokens.controlRadius, borderWidth: 0, alignItems: 'center', backgroundColor: { default: tokens.transparent, ':hover': tokens.accent }, color: tokens.mutedForeground, cursor: interactionTokens.cursorAction, display: 'flex', justifyContent: 'center', position: 'relative', height: '2rem', width: '2rem', },
  activeFilterWrap: { position: 'relative' },
  filterBadge: { borderRadius: '50%', alignItems: 'center', backgroundColor: tokens.primary, color: tokens.primaryForeground, display: 'flex', fontSize: '0.625rem', fontWeight: 700, justifyContent: 'center', position: 'absolute', height: '1rem', right: '-0.25rem', top: '-0.25rem', width: '1rem', },
  activeFilterPanel: { padding: '0.5rem', borderColor: tokens.border, borderRadius: tokens.radius, borderStyle: 'solid', borderWidth: 1, gap: '0.25rem', backgroundColor: tokens.card, boxShadow: tokens.shadowCard, display: 'grid', position: 'absolute', zIndex: 60, left: 'calc(100% + 0.5rem)', top: 0, width: '16rem', },
  activeFilterItem: { gap: '0.5rem',
 paddingBlock: '0.375rem',
 paddingInline: '0.5rem',
 alignItems: 'center',
 display: 'flex',
 justifyContent: 'space-between', },
  activeFilterText: { display: 'flex', flexDirection: 'column', fontSize: '0.75rem', minWidth: 0 },
  iconButton: { padding: 0, borderWidth: 0, alignItems: 'center', backgroundColor: tokens.transparent, color: tokens.mutedForeground, cursor: interactionTokens.cursorAction, display: 'inline-flex', justifyContent: 'center', height: '1.75rem', width: '1.75rem', },
  backdrop: { inset: 0, padding: 0, borderWidth: 0, backgroundColor: tokens.transparent, position: 'fixed', zIndex: 40, },
  filterBackdrop: { zIndex: 15 },
  pageSizeWrap: { gap: '0.375rem', alignItems: 'center', display: 'flex', position: 'relative', zIndex: 45, },
  pageSizeInput: { borderColor: tokens.border, borderRadius: tokens.controlRadius, borderStyle: 'solid', borderWidth: 1, paddingInline: '0.5rem', backgroundColor: tokens.background, color: tokens.foreground, fontSize: '0.75rem', height: '1.75rem', width: '5rem', },
  pageSizePanel: { borderColor: tokens.border, borderRadius: tokens.radius, borderStyle: 'solid', borderWidth: 1, paddingBlock: '0.25rem', backgroundColor: tokens.card, boxShadow: tokens.shadowCard, position: 'absolute', zIndex: 60, bottom: 'calc(100% + 0.25rem)', left: 0, minWidth: '5rem', },
  pageSizeOption: { borderWidth: 0, paddingInline: '0.75rem', backgroundColor: { default: tokens.transparent, ':hover': complexTokens.mutedSurface }, color: tokens.foreground, cursor: interactionTokens.cursorAction, display: 'block', fontSize: '0.75rem', textAlign: 'left', minHeight: '1.75rem', width: '100%', },
  pageSizeOptionActive: { backgroundColor: complexTokens.accentSurface, color: tokens.primary, fontWeight: 600 },
  loading: { gap: '0.5rem',
 alignItems: 'center',
 color: tokens.mutedForeground,
 display: 'flex',
 flexBasis: '0%',
 flexGrow: '1',
 flexShrink: '1',
 fontSize: '0.875rem',
 justifyContent: 'center',
 minHeight: '14rem', },
  spinner: { animationDuration: interactionTokens.motionLoopFast, animationIterationCount: 'infinite', animationName: spin, animationTimingFunction: interactionTokens.easingLinear, height: '1rem', width: '1rem' },
  empty: { padding: '2rem', color: tokens.mutedForeground, fontSize: '0.875rem', textAlign: 'center', },
  smallIcon: { height: '0.875rem', width: '0.875rem' },
  tinyIcon: { height: '0.75rem', width: '0.75rem' },
})

