import { installStyleXExamplePreviewProvider } from '@/docs/components/catalog';
import { accordionStyleXPreview } from '@/docs/components/pages/accordion/stylex';
import { alertStyleXPreview } from '@/docs/components/pages/alert/stylex';
import { aspectRatioStyleXPreview } from '@/docs/components/pages/aspect-ratio/stylex';
import { avatarStyleXPreview } from '@/docs/components/pages/avatar/stylex';
import { badgeStyleXPreview } from '@/docs/components/pages/badge/stylex';
import { breadcrumbStyleXPreview } from '@/docs/components/pages/breadcrumb/stylex';
import { kbdStyleXPreview } from '@/docs/components/pages/kbd/stylex';
import { labelStyleXPreview } from '@/docs/components/pages/label/stylex';
import { markerStyleXPreview } from '@/docs/components/pages/marker/stylex';
import { separatorStyleXPreview } from '@/docs/components/pages/separator/stylex';
import { skeletonStyleXPreview } from '@/docs/components/pages/skeleton/stylex';
import { spinnerStyleXPreview } from '@/docs/components/pages/spinner/stylex';
import { typographyStyleXPreview } from '@/docs/components/pages/typography/stylex';
import { buttonStyleXPreview } from '@/docs/components/pages/button/stylex';
import { buttonGroupStyleXPreview } from '@/docs/components/pages/button-group/stylex';
import { inputStyleXPreview } from '@/docs/components/pages/input/stylex';
import { inputOtpStyleXPreview } from '@/docs/components/pages/input-otp/stylex';
import { textareaStyleXPreview } from '@/docs/components/pages/textarea/stylex';
import { toggleStyleXPreview } from '@/docs/components/pages/toggle/stylex';
import { toggleGroupStyleXPreview } from '@/docs/components/pages/toggle-group/stylex';
import { checkboxStyleXPreview } from '@/docs/components/pages/checkbox/stylex';
import { switchStyleXPreview } from '@/docs/components/pages/switch/stylex';
import { radioGroupStyleXPreview } from '@/docs/components/pages/radio-group/stylex';
import { nativeSelectStyleXPreview } from '@/docs/components/pages/native-select/stylex';
import { progressStyleXPreview } from '@/docs/components/pages/progress/stylex';
import { sliderStyleXPreview } from '@/docs/components/pages/slider/stylex';
import { collapsibleStyleXPreview } from '@/docs/components/pages/collapsible/stylex';
import { dialogStyleXPreview } from '@/docs/components/pages/dialog/stylex';
import { alertDialogStyleXPreview } from '@/docs/components/pages/alert-dialog/stylex';
import { drawerStyleXPreview } from '@/docs/components/pages/drawer/stylex';
import { sheetStyleXPreview } from '@/docs/components/pages/sheet/stylex';
import { popoverStyleXPreview } from '@/docs/components/pages/popover/stylex';
import { hoverCardStyleXPreview } from '@/docs/components/pages/hover-card/stylex';
import { tooltipStyleXPreview } from '@/docs/components/pages/tooltip/stylex';
import { dropdownMenuStyleXPreview } from '@/docs/components/pages/dropdown-menu/stylex';
import { contextMenuStyleXPreview } from '@/docs/components/pages/context-menu/stylex';
import { menubarStyleXPreview } from '@/docs/components/pages/menubar/stylex';
import { navigationMenuStyleXPreview } from '@/docs/components/pages/navigation-menu/stylex';
import { selectStyleXPreview } from '@/docs/components/pages/select/stylex';
import { comboboxStyleXPreview } from '@/docs/components/pages/combobox/stylex';
import { commandStyleXPreview } from '@/docs/components/pages/command/stylex';
import { attachmentStyleXPreview } from '@/docs/components/pages/attachment/stylex';
import { bubbleStyleXPreview } from '@/docs/components/pages/bubble/stylex';
import { cardStyleXPreview } from '@/docs/components/pages/card/stylex';
import { emptyStyleXPreview } from '@/docs/components/pages/empty/stylex';
import { itemStyleXPreview } from '@/docs/components/pages/item/stylex';
import { messageStyleXPreview } from '@/docs/components/pages/message/stylex';

installStyleXExamplePreviewProvider('accordion', accordionStyleXPreview);
installStyleXExamplePreviewProvider('alert', alertStyleXPreview);
installStyleXExamplePreviewProvider('aspect-ratio', aspectRatioStyleXPreview);
installStyleXExamplePreviewProvider('avatar', avatarStyleXPreview);
installStyleXExamplePreviewProvider('badge', badgeStyleXPreview);
installStyleXExamplePreviewProvider('breadcrumb', breadcrumbStyleXPreview);
installStyleXExamplePreviewProvider('kbd', kbdStyleXPreview);
installStyleXExamplePreviewProvider('label', labelStyleXPreview);
installStyleXExamplePreviewProvider('marker', markerStyleXPreview);
installStyleXExamplePreviewProvider('separator', separatorStyleXPreview);
installStyleXExamplePreviewProvider('skeleton', skeletonStyleXPreview);
installStyleXExamplePreviewProvider('spinner', spinnerStyleXPreview);
installStyleXExamplePreviewProvider('typography', typographyStyleXPreview);
installStyleXExamplePreviewProvider('button', buttonStyleXPreview);
installStyleXExamplePreviewProvider('button-group', buttonGroupStyleXPreview);
installStyleXExamplePreviewProvider('input', inputStyleXPreview);
installStyleXExamplePreviewProvider('input-otp', inputOtpStyleXPreview);
installStyleXExamplePreviewProvider('textarea', textareaStyleXPreview);
installStyleXExamplePreviewProvider('toggle', toggleStyleXPreview);
installStyleXExamplePreviewProvider('toggle-group', toggleGroupStyleXPreview);
installStyleXExamplePreviewProvider('checkbox', checkboxStyleXPreview);
installStyleXExamplePreviewProvider('switch', switchStyleXPreview);
installStyleXExamplePreviewProvider('radio-group', radioGroupStyleXPreview);
installStyleXExamplePreviewProvider('native-select', nativeSelectStyleXPreview);
installStyleXExamplePreviewProvider('progress', progressStyleXPreview);
installStyleXExamplePreviewProvider('slider', sliderStyleXPreview);
installStyleXExamplePreviewProvider('collapsible', collapsibleStyleXPreview);
installStyleXExamplePreviewProvider('dialog', dialogStyleXPreview);
installStyleXExamplePreviewProvider('alert-dialog', alertDialogStyleXPreview);
installStyleXExamplePreviewProvider('drawer', drawerStyleXPreview);
installStyleXExamplePreviewProvider('sheet', sheetStyleXPreview);
installStyleXExamplePreviewProvider('popover', popoverStyleXPreview);
installStyleXExamplePreviewProvider('hover-card', hoverCardStyleXPreview);
installStyleXExamplePreviewProvider('tooltip', tooltipStyleXPreview);
installStyleXExamplePreviewProvider('dropdown-menu', dropdownMenuStyleXPreview);
installStyleXExamplePreviewProvider('context-menu', contextMenuStyleXPreview);
installStyleXExamplePreviewProvider('menubar', menubarStyleXPreview);
installStyleXExamplePreviewProvider('navigation-menu', navigationMenuStyleXPreview);
installStyleXExamplePreviewProvider('select', selectStyleXPreview);
installStyleXExamplePreviewProvider('combobox', comboboxStyleXPreview);
installStyleXExamplePreviewProvider('command', commandStyleXPreview);
installStyleXExamplePreviewProvider('attachment', attachmentStyleXPreview);
installStyleXExamplePreviewProvider('bubble', bubbleStyleXPreview);
installStyleXExamplePreviewProvider('card', cardStyleXPreview);
installStyleXExamplePreviewProvider('empty', emptyStyleXPreview);
installStyleXExamplePreviewProvider('item', itemStyleXPreview);
installStyleXExamplePreviewProvider('message', messageStyleXPreview);
