import { installStyleXExamplePreviewProvider } from '@/docs/components/catalog';
import { accordionStyleXPreview } from '@/docs/components/pages/accordion/stylex';
import { alertStyleXPreview } from '@/docs/components/pages/alert/stylex';
import { aspectRatioStyleXPreview } from '@/docs/components/pages/aspect-ratio/stylex';
import { avatarStyleXPreview } from '@/docs/components/pages/avatar/stylex';
import { badgeStyleXPreview } from '@/docs/components/pages/badge/stylex';
import { breadcrumbStyleXPreview } from '@/docs/components/pages/breadcrumb/stylex';
import { kbdStyleXPreview } from '@/docs/components/pages/kbd/stylex';
import { labelStyleXPreview } from '@/docs/components/pages/label/stylex';
import { markerStyleXPreview } from '@/docs/components/pages/marker/stylex';
import { separatorStyleXPreview } from '@/docs/components/pages/separator/stylex';
import { skeletonStyleXPreview } from '@/docs/components/pages/skeleton/stylex';
import { spinnerStyleXPreview } from '@/docs/components/pages/spinner/stylex';
import { typographyStyleXPreview } from '@/docs/components/pages/typography/stylex';
import { buttonStyleXPreview } from '@/docs/components/pages/button/stylex';
import { buttonGroupStyleXPreview } from '@/docs/components/pages/button-group/stylex';
import { inputStyleXPreview } from '@/docs/components/pages/input/stylex';
import { inputOtpStyleXPreview } from '@/docs/components/pages/input-otp/stylex';
import { textareaStyleXPreview } from '@/docs/components/pages/textarea/stylex';
import { toggleStyleXPreview } from '@/docs/components/pages/toggle/stylex';
import { toggleGroupStyleXPreview } from '@/docs/components/pages/toggle-group/stylex';
import { checkboxStyleXPreview } from '@/docs/components/pages/checkbox/stylex';
import { switchStyleXPreview } from '@/docs/components/pages/switch/stylex';
import { radioGroupStyleXPreview } from '@/docs/components/pages/radio-group/stylex';
import { nativeSelectStyleXPreview } from '@/docs/components/pages/native-select/stylex';

installStyleXExamplePreviewProvider('accordion', accordionStyleXPreview);
installStyleXExamplePreviewProvider('alert', alertStyleXPreview);
installStyleXExamplePreviewProvider('aspect-ratio', aspectRatioStyleXPreview);
installStyleXExamplePreviewProvider('avatar', avatarStyleXPreview);
installStyleXExamplePreviewProvider('badge', badgeStyleXPreview);
installStyleXExamplePreviewProvider('breadcrumb', breadcrumbStyleXPreview);
installStyleXExamplePreviewProvider('kbd', kbdStyleXPreview);
installStyleXExamplePreviewProvider('label', labelStyleXPreview);
installStyleXExamplePreviewProvider('marker', markerStyleXPreview);
installStyleXExamplePreviewProvider('separator', separatorStyleXPreview);
installStyleXExamplePreviewProvider('skeleton', skeletonStyleXPreview);
installStyleXExamplePreviewProvider('spinner', spinnerStyleXPreview);
installStyleXExamplePreviewProvider('typography', typographyStyleXPreview);
installStyleXExamplePreviewProvider('button', buttonStyleXPreview);
installStyleXExamplePreviewProvider('button-group', buttonGroupStyleXPreview);
installStyleXExamplePreviewProvider('input', inputStyleXPreview);
installStyleXExamplePreviewProvider('input-otp', inputOtpStyleXPreview);
installStyleXExamplePreviewProvider('textarea', textareaStyleXPreview);
installStyleXExamplePreviewProvider('toggle', toggleStyleXPreview);
installStyleXExamplePreviewProvider('toggle-group', toggleGroupStyleXPreview);
installStyleXExamplePreviewProvider('checkbox', checkboxStyleXPreview);
installStyleXExamplePreviewProvider('switch', switchStyleXPreview);
installStyleXExamplePreviewProvider('radio-group', radioGroupStyleXPreview);
installStyleXExamplePreviewProvider('native-select', nativeSelectStyleXPreview);
