import type { DocsExample } from '@/docs/components/page-definition'; import { foldkitApplication } from '@/docs/components/pages/authored-page';
export const settingsTabs = [{ value: 'account', label: 'Account', content: 'Manage your profile details.' }, { value: 'security', label: 'Security', content: 'Review passwords and sessions.' }, { value: 'billing', label: 'Billing', content: 'Update invoices and payment methods.' }] as const;
export const projectTabs = [{ value: 'overview', label: 'Overview', content: 'Project activity and health.' }, { value: 'deployments', label: 'Deployments', content: 'Recent production releases.' }, { value: 'settings', label: 'Settings', content: 'Project-level configuration.' }] as const;
export const tabsFixtures = [
  { title: 'Settings', description: 'Child update manages focus while the parent persists the selected domain value.', set: 'settings', initial: 'account', variant: 'default', manual: false, rtl: false },
  { title: 'Line variant', description: 'A separate child instance needs its own id, Model, Message routing, and selected value.', set: 'project', initial: 'overview', variant: 'line', manual: false, rtl: false },
  { title: 'Manual with disabled tab', description: 'Manual activation moves focus without changing the parent-owned value until Enter or Space; disabled tabs are skipped.', set: 'settings', initial: 'account', variant: 'default', manual: true, rtl: false },
  { title: 'RTL route value', description: 'The selected route remains parent-owned while horizontal tab order and arrow direction mirror in RTL.', set: 'project', initial: 'settings', variant: 'default', manual: false, rtl: true },
] as const;
const source = (fixture: (typeof tabsFixtures)[number], renderer: 'tailwind' | 'stylex'): string => { const tag = fixture.title.replaceAll(/[^a-zA-Z0-9]/g, ''); const configs = fixture.set === 'settings' ? settingsTabs : projectTabs; const tabSource = configs.map(tab => `        { value: '${tab.value}', label: '${tab.label}', content: '${tab.content}'${fixture.manual && tab.value === 'security' ? ', isDisabled: true' : ''} },`).join('\n'); return foldkitApplication({ title: `Tabs — ${fixture.title}`, imports: `import { Option, Schema as S } from 'effect'\nimport { Command, Runtime, Subscription } from 'foldkit'\nimport { type Document, type HtmlBuilder } from 'foldkit/html'\nimport { m } from 'foldkit/message'\n\nimport * as Tabs from '@/${renderer === 'stylex' ? 'stylex' : 'ui'}/tabs'`, model: `export const TabValue = S.Literals(['account', 'security', 'billing', 'overview', 'deployments', 'settings'])\nexport type TabValue = typeof TabValue.Type\nconst SettingsTabs = Tabs.create<TabValue>()\nexport const Model = S.Struct({ tabs: Tabs.Model, selectedTab: TabValue })\nexport type Model = typeof Model.Type`, messages: `export const GotTabsMessage = m('GotTabsMessage${tag}', { message: Tabs.Message })\nexport const Message = S.Union([GotTabsMessage])\nexport type Message = typeof Message.Type`, init: `export const init = (): readonly [Model, ReadonlyArray<Command.Command<Message>>] => [\n  { tabs: Tabs.init({ id: 'settings-tabs'${fixture.manual ? ", activationMode: 'Manual'" : ''} }), selectedTab: '${fixture.initial}' },\n  [],\n]`, update: `export const update = (model: Model, message: Message): readonly [Model, ReadonlyArray<Command.Command<Message>>] => {\n  switch (message._tag) {\n    case 'GotTabsMessage${tag}': {\n      const [tabs, commands, maybeSelection] = SettingsTabs.update(model.tabs, message.message)\n      return [{ ...model, tabs, selectedTab: Option.match(maybeSelection, { onNone: () => model.selectedTab, onSome: selection => selection.value }) }, Command.mapMessages(commands, next => GotTabsMessage({ message: next }))]\n    }\n  }\n}`, view: `export const view = (model: Model, h: HtmlBuilder<Message>): Document => ({\n  title: 'Tabs — ${fixture.title}',\n  body: h.main([h.Class('mx-auto max-w-xl p-8')], [\n    SettingsTabs.tabs({ model: model.tabs, selectedValue: model.selectedTab, toParentMessage: message => GotTabsMessage({ message }), ariaLabel: '${fixture.set === 'settings' ? 'Settings' : 'Project sections'}', tabs: [\n${tabSource}\n      ],${fixture.variant === 'line' ? "\n      variant: 'line'," : ''}${fixture.rtl ? "\n      direction: 'rtl'," : ''}\n    }, h),\n  ]),\n})` }); };
export const tabsExamples = (renderer: 'tailwind' | 'stylex'): ReadonlyArray<DocsExample> => tabsFixtures.map(fixture => ({ title: fixture.title, description: fixture.description, code: source(fixture, renderer) }));
