import type { DocsExample } from '@/docs/components/page-definition';
import { controlledTextApplication } from '@/docs/components/pages/authored-page';

export const textareaInitialValues = [
  '',
  'Too short',
  'This value is generated by the build.',
  'First line\nSecond line',
] as const;

const metadata = [
  {
    title: 'Message',
    description: 'Keep multi-line content in the parent Model like any other controlled value.',
    label: 'Message',
    config: `label: 'Message',
  description: 'Include enough context for the reviewer.',
  placeholder: 'Describe the change…',
  rows: 4,`,
  },
  {
    title: 'Invalid',
    description: 'Pair invalid state with specific correction guidance.',
    label: 'Release notes',
    config: `label: 'Release notes',
  description: 'Release notes must contain at least 20 characters.',
  isInvalid: true,`,
  },
  {
    title: 'Disabled',
    description: 'Disabled state prevents editing without discarding controlled text.',
    label: 'Generated summary',
    config: `label: 'Generated summary',
  isDisabled: true,`,
  },
  {
    title: 'Form and resize',
    description: 'Associate multiline content with a native form and select one finite resize policy without changing value ownership.',
    label: 'Deployment notes',
    config: `label: 'Deployment notes',
  name: 'notes',
  form: 'textarea-profile',
  rows: 5,
  wrap: 'hard',
  resize: 'none',
  isReadOnly: true,`,
  },
] as const;

export const textareaLabel = (index: number): string =>
  (metadata[index] ?? metadata[0]).label;

export const textareaExamples = (
  renderer: 'tailwind' | 'stylex',
): ReadonlyArray<DocsExample> => metadata.map((item, index) => ({
  title: item.title,
  description: item.description,
  code: controlledTextApplication({
    componentName: 'Textarea',
    componentSlug: 'textarea',
    renderer,
    exampleName: item.title,
    field: 'message',
    initialValue: textareaInitialValues[index] ?? '',
    ...(renderer === 'stylex'
      ? {
          componentImports: `import * as stylex from '@stylexjs/stylex'

const styles = stylex.create({ textarea: { maxWidth: '28rem' } })`,
        }
      : {}),
    viewBody: `Textarea.textarea({
  id: 'message',
  value: model.message,
  onInput: value => ChangedTextarea({ value }),
  ${item.config}
  ${renderer === 'tailwind' ? "class: 'max-w-md'," : 'layoutStyle: styles.textarea,'}
}, h),`,
  }),
}));
