import type { LocaleConfig } from 'foldkit/calendar'; import type { DocsExample } from '@/docs/components/page-definition'; import { foldkitApplication } from '@/docs/components/pages/authored-page';
export const germanCalendarLocale: LocaleConfig = { firstDayOfWeek: 'Monday', monthNames: ['Januar', 'Februar', 'März', 'April', 'Mai', 'Juni', 'Juli', 'August', 'September', 'Oktober', 'November', 'Dezember'], shortMonthNames: ['Jan', 'Feb', 'Mär', 'Apr', 'Mai', 'Jun', 'Jul', 'Aug', 'Sep', 'Okt', 'Nov', 'Dez'], dayNames: ['Sonntag', 'Montag', 'Dienstag', 'Mittwoch', 'Donnerstag', 'Freitag', 'Samstag'], shortDayNames: ['So', 'Mo', 'Di', 'Mi', 'Do', 'Fr', 'Sa'] };
export const calendarFixtures = [
  { title: 'Selected date', description: 'The parent stores the selected date emitted by the child while Calendar keeps focus and navigation state.', roomy: false, range: false, localized: false },
  { title: 'Roomier cells', description: 'View density changes through a CSS token; the Model, Message, update, and output contract stay identical.', roomy: true, range: false, localized: false },
  { title: 'Parent-owned range', description: 'The parent owns both range endpoints; Calendar only decorates the corresponding day cells while retaining one focused cursor.', roomy: false, range: true, localized: false },
  { title: 'Locale zone and RTL', description: 'Locale data is serializable, the parent converts instants in an explicit time zone, and direction mirrors navigation without changing chronology.', roomy: false, range: false, localized: true },
] as const;
const source = (f: (typeof calendarFixtures)[number], renderer: 'tailwind' | 'stylex'): string => { const tag = f.title.replaceAll(/[^a-zA-Z0-9]/g, ''); return foldkitApplication({ title: `Calendar — ${f.title}`, imports: `import { Option, Schema as S } from 'effect'\nimport { Command, Runtime, Subscription } from 'foldkit'\nimport * as FoldkitCalendar from 'foldkit/calendar'\nimport { type Document, type HtmlBuilder } from 'foldkit/html'\nimport { m } from 'foldkit/message'\n\nimport * as Calendar from '@/${renderer === 'stylex' ? 'stylex' : 'ui'}/calendar'`, model: `${f.localized ? `const locale: FoldkitCalendar.LocaleConfig = ${JSON.stringify(germanCalendarLocale)}\n\n` : ''}export const Model = S.Struct({ calendar: Calendar.Model, selectedDate: S.Option(FoldkitCalendar.CalendarDate), rangeStart: FoldkitCalendar.CalendarDate, rangeEnd: FoldkitCalendar.CalendarDate })\nexport type Model = typeof Model.Type`, messages: `export const GotCalendarMessage = m('GotCalendarMessage${tag}', { message: Calendar.Message })\nexport const Message = S.Union([GotCalendarMessage])\nexport type Message = typeof Message.Type`, init: `const initialDate = { year: 2026, month: 7, day: 18 }\nexport const init = (): readonly [Model, ReadonlyArray<Command.Command<Message>>] => [{ calendar: Calendar.init({ id: 'booking-calendar', today: Calendar.dateInTimeZone(new Date('2026-07-28T12:00:00Z'), '${f.localized ? 'Europe/Berlin' : 'UTC'}'), initialViewDate: initialDate, ${f.localized ? 'locale' : "disabledDaysOfWeek: ['Sunday']"} }), selectedDate: Option.some(initialDate), rangeStart: { year: 2026, month: 7, day: 14 }, rangeEnd: { year: 2026, month: 7, day: 20 } }, []]`, update: `export const update = (model: Model, message: Message): readonly [Model, ReadonlyArray<Command.Command<Message>>] => {\n  switch (message._tag) {\n    case 'GotCalendarMessage${tag}': {\n      const [calendar, commands, maybeOutput] = Calendar.update(model.calendar, message.message)\n      const selectedDate = Option.match(maybeOutput, { onNone: () => model.selectedDate, onSome: output => output._tag === 'SelectedDate' ? Option.some(output.date) : model.selectedDate })\n      return [{ ...model, calendar, selectedDate }, Command.mapMessages(commands, next => GotCalendarMessage({ message: next }))]\n    }\n  }\n}`, view: `export const view = (model: Model, h: HtmlBuilder<Message>): Document => ({ title: 'Calendar — ${f.title}', body: h.main([h.Class('flex min-h-screen items-center justify-center p-8')], [Calendar.calendar({ model: model.calendar, maybeSelectedDate: model.selectedDate, toParentMessage: message => GotCalendarMessage({ message })${f.roomy ? renderer === 'stylex' ? ", size: 'comfortable'" : ", class: '[--cell-size:--spacing(10)]'" : ''}${f.range ? ', range: { start: model.rangeStart, end: model.rangeEnd }' : ''}${f.localized ? ", direction: 'rtl'" : ''} }, h)]) })` }); };
export const calendarExamples = (renderer: 'tailwind' | 'stylex'): ReadonlyArray<DocsExample> => calendarFixtures.map(f => ({ title: f.title, description: f.description, code: source(f, renderer) }));
