import * as stylex from '@stylexjs/stylex'

import { complexTokens } from '../complex-tokens.stylex'
import { interactionTokens } from '../interaction-tokens.stylex.const'
import { tokens } from '../tokens.stylex'

export const styles = stylex.create({
  root: { gap: '1rem', display: 'flex', flexDirection: 'column', minWidth: 0, width: '100%', },
  toolbar: { gap: '0.75rem', alignItems: 'center', display: 'flex', flexWrap: 'wrap', justifyContent: 'space-between', },
  filter: {
    borderColor: { default: tokens.input, ':focus-visible': tokens.ring },
    borderRadius: tokens.controlRadius,
    borderStyle: 'solid',
    borderWidth: 1,
    paddingInline: '0.75rem',
    backgroundColor: tokens.transparent,
    boxShadow: { default: tokens.shadowSm, ':focus-visible': tokens.focusRingShadow },
    fontSize: '0.875rem',
    outlineStyle: 'none',
    height: '2.5rem',
    maxWidth: '24rem',
    width: '100%',
  },
  summary: { color: tokens.mutedForeground, fontSize: '0.8125rem', fontVariantNumeric: 'tabular-nums', whiteSpace: 'nowrap' },
  shell: {
    borderColor: tokens.border,
    borderRadius: tokens.cardRadius,
    borderStyle: 'solid',
    borderWidth: 1,
    overflow: 'hidden',
    boxShadow: tokens.shadowSm,
    minWidth: 0,
  },
  horizontalScroll: { minWidth: 0, overflowX: 'auto' },
  table: { minWidth: '58rem', width: '100%' },
  header: {
    alignItems: 'center',
    backgroundColor: complexTokens.mutedSurface,
    display: 'grid',
    borderBottomColor: tokens.border,
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
    minHeight: '2.75rem',
  },
  heading: {
    paddingInline: '0.75rem',
    alignItems: 'center',
    color: tokens.mutedForeground,
    display: 'flex',
    fontSize: '0.6875rem',
    fontWeight: 600,
    letterSpacing: '0.055em',
    textTransform: 'uppercase',
    minWidth: 0,
  },
  sortButton: {
    borderRadius: tokens.controlRadius,
    gap: '0.375rem',
    alignItems: 'center',
    color: { default: tokens.mutedForeground, ':hover': tokens.foreground },
    cursor: interactionTokens.cursorAction,
    display: 'inline-flex',
    outlineColor: { default: tokens.transparent, ':focus-visible': tokens.ring },
    outlineStyle: { default: 'none', ':focus-visible': 'solid' },
    outlineWidth: { default: 0, ':focus-visible': 2 },
    transform: { default: 'scale(1)', ':active': interactionTokens.pressTransformTactile },
    transitionDuration: interactionTokens.motionFast,
    transitionProperty: 'color, transform',
    minHeight: '2.5rem',
  },
  sortIcon: { height: '0.875rem', width: '0.875rem' },
  viewport: { overscrollBehavior: 'contain', height: '26rem', },
  row: {
    alignItems: 'center',
    backgroundColor: { default: tokens.transparent, ':hover': complexTokens.mutedSurface },
    display: 'grid',
    transitionDuration: interactionTokens.motionFast,
    transitionProperty: 'background-color',
    borderBottomColor: tokens.border,
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
    height: '100%',
  },
  rowSelected: { backgroundColor: complexTokens.mutedSurface },
  cell: { overflow: 'hidden', paddingInline: '0.75rem', fontSize: '0.8125rem', textOverflow: 'ellipsis', whiteSpace: 'nowrap', minWidth: 0, },
  numeric: { fontVariantNumeric: 'tabular-nums' },
  selectionCell: { padding: 0, alignItems: 'center', display: 'flex', justifyContent: 'center', },
  selectionButton: {
    padding: 0,
    borderWidth: 0,
    alignItems: 'center',
    backgroundColor: tokens.transparent,
    display: 'inline-flex',
    justifyContent: 'center',
    height: '2.5rem',
    width: '2.5rem',
  },
  selectionBox: {
    borderColor: tokens.input,
    borderRadius: complexTokens.smallRadius,
    borderStyle: 'solid',
    borderWidth: 1,
    alignItems: 'center',
    backgroundColor: tokens.background,
    color: tokens.primaryForeground,
    display: 'flex',
    justifyContent: 'center',
    height: '1rem',
    width: '1rem',
  },
  selectionBoxChecked: { borderColor: tokens.primary, backgroundColor: tokens.primary, },
  selectionIcon: { height: '0.75rem', width: '0.75rem' },
  empty: { alignItems: 'center', color: tokens.mutedForeground, display: 'flex', fontSize: '0.875rem', justifyContent: 'center', height: '8rem', },
})

