import type { DocsExample } from '@/docs/components/page-definition'; import { foldkitApplication } from '@/docs/components/pages/authored-page'; import { notificationExamples, type NotificationConfig } from '@/docs/components/pages/notification-page';
export const sonnerConfig: NotificationConfig = { slug: 'sonner', title: 'Sonner', namespace: 'Sonner', kind: 'submodel', description: 'A compatibility skin over the canonical Toast notification Submodel, not a second state engine.' };
const asyncSource = (renderer: 'tailwind' | 'stylex'): string => foldkitApplication({ title: 'Sonner — Async save migration', imports: `import { Effect, Option, Schema as S } from 'effect'\nimport { Command, Runtime, Subscription, Update } from 'foldkit'\nimport { type Document, type HtmlBuilder } from 'foldkit/html'\nimport { defineMessageUnion } from 'foldkit/message'\n\nimport * as Button from '@/${renderer === 'stylex' ? 'stylex' : 'ui'}/button'\nimport * as Sonner from '@/${renderer === 'stylex' ? 'stylex' : 'ui'}/sonner'`, model: `export const Model = S.Struct({ notifications: Sonner.Model, activeToastId: S.Option(S.String) })\nexport type Model = typeof Model.Type`, messages: `import { defineMessageUnion } from 'foldkit/message'
\n\n\nexport const Message = defineMessageUnion({
  ClickedSave: {},
  CompletedSave: {},
  GotSonnerMessage: { message: Sonner.Message },
});\nexport type Message = typeof Message.Type`, init: `export const init = (): Update.Return<Model, Message> => ({ model: { notifications: Sonner.init({ id: 'save-notifications' }), activeToastId: Option.none() } })`, update: `const Save = Command.define('Save', { messages: [Message.CompletedSave], execute: Effect.sleep('600 millis').pipe(Effect.as(Message.CompletedSave())) })\nconst mapNotifications = (model: Model, result: ReturnType<typeof Sonner.update>): Update.Return<Model, Message> => ({ model: { ...model, notifications: result.model }, commands: Command.mapMessages(result.commands, message => Message.GotSonnerMessage({ message })) })\nexport const update = (model: Model, message: Message): Update.Return<Model, Message> => { switch (message._tag) { case 'ClickedSave': { const result = Sonner.show(model.notifications, Sonner.info({ title: 'Saving changes…', sticky: true })); const mapped = mapNotifications(model, result); const next = mapped.model; const commands = mapped.commands ?? []; const activeToastId = Option.fromNullishOr(next.notifications.entries.at(-1)?.id); return { model: { ...next, activeToastId }, commands: [...commands, Save()] } } case 'CompletedSave': return Option.match(model.activeToastId, { onNone: () => ({ model: model }) as const, onSome: id => mapNotifications({ ...model, activeToastId: Option.none() }, Sonner.updateToast(model.notifications, id, { title: 'Changes saved', variant: 'Success', sticky: false, duration: '3 seconds' })) }); case 'GotSonnerMessage': return mapNotifications(model, Sonner.update(model.notifications, message.message)) } }`, view: `export const view = (model: Model, h: HtmlBuilder<Message>): Document => ({ title: 'Sonner — Async save migration', body: h.main([], [Button.button({ onClick: Message.ClickedSave(), children: ['Save changes'] }, h), Sonner.sonner({ model: model.notifications, toParentMessage: message => Message.GotSonnerMessage({ message }) }, h)]) })` });
export const sonnerExamples = (renderer: 'tailwind' | 'stylex'): ReadonlyArray<DocsExample> => [...notificationExamples(sonnerConfig, renderer), { title: 'Async save migration', description: 'Replace imperative toast.promise calls with a parent Command and updateToast on the stable keyed entry.', code: asyncSource(renderer) }, { title: 'Imperative API migration', description: 'Global toast(), dismiss(), and promise() calls are intentionally unsupported; keep notification state in the parent and call show, updateToast, or dismiss from update.', code: asyncSource(renderer) }];
