// Generated by npm run icons:adapters:generate. Do not edit manually.
export const iconNodes = {
  "arrow-down": {
    "width": 24,
    "height": 24,
    "nodes": [
      [
        "path",
        {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M12 5v14m6-6l-6 6m-6-6l6 6"
        },
        []
      ]
    ]
  },
  "arrow-left": {
    "width": 24,
    "height": 24,
    "nodes": [
      [
        "path",
        {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M5 12h14M5 12l6 6m-6-6l6-6"
        },
        []
      ]
    ]
  },
  "arrow-right": {
    "width": 24,
    "height": 24,
    "nodes": [
      [
        "path",
        {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M5 12h14m-6 6l6-6m-6-6l6 6"
        },
        []
      ]
    ]
  },
  "audio-waveform": {
    "width": 24,
    "height": 24,
    "nodes": [
      [
        "path",
        {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M21 12h-2c-.894 0-1.662-.857-1.761-2c-.296-3.45-.749-6-2.749-6s-2.5 3.582-2.5 8s-.5 8-2.5 8s-2.452-2.547-2.749-6c-.1-1.147-.867-2-1.763-2h-2"
        },
        []
      ]
    ]
  },
  "blocks": {
    "width": 24,
    "height": 24,
    "nodes": [
      [
        "path",
        {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M14 4a1 1 0 0 1 1-1h5a1 1 0 0 1 1 1v5a1 1 0 0 1-1 1h-5a1 1 0 0 1-1-1zM3 14h12a2 2 0 0 1 2 2v3a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V9a2 2 0 0 1 2-2h3a2 2 0 0 1 2 2v12"
        },
        []
      ]
    ]
  },
  "bold": {
    "width": 24,
    "height": 24,
    "nodes": [
      [
        "path",
        {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M7 5h6a3.5 3.5 0 0 1 0 7H7zm6 7h1a3.5 3.5 0 0 1 0 7H7v-7"
        },
        []
      ]
    ]
  },
  "book-open": {
    "width": 24,
    "height": 24,
    "nodes": [
      [
        "path",
        {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M3 19a9 9 0 0 1 9 0a9 9 0 0 1 9 0M3 6a9 9 0 0 1 9 0a9 9 0 0 1 9 0M3 6v13m9-13v13m9-13v13"
        },
        []
      ]
    ]
  },
  "bot": {
    "width": 24,
    "height": 24,
    "nodes": [
      [
        "path",
        {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M6 6a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v4a2 2 0 0 1-2 2H8a2 2 0 0 1-2-2zm6-4v2m-3 8v9m6-9v9M5 16l4-2m6 0l4 2M9 18h6M10 8v.01M14 8v.01"
        },
        []
      ]
    ]
  },
  "calendar": {
    "width": 24,
    "height": 24,
    "nodes": [
      [
        "path",
        {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M4 7a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2zm12-4v4M8 3v4m-4 4h16m-9 4h1m0 0v3"
        },
        []
      ]
    ]
  },
  "car": {
    "width": 24,
    "height": 24,
    "nodes": [
      [
        "g",
        {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2"
        },
        [
          [
            "path",
            {
              "d": "M5 17a2 2 0 1 0 4 0a2 2 0 1 0-4 0m10 0a2 2 0 1 0 4 0a2 2 0 1 0-4 0"
            },
            []
          ],
          [
            "path",
            {
              "d": "M5 17H3v-6l2-5h9l4 5h1a2 2 0 0 1 2 2v4h-2m-4 0H9m-6-6h15m-6 0V6"
            },
            []
          ]
        ]
      ]
    ]
  },
  "chart-pie": {
    "width": 24,
    "height": 24,
    "nodes": [
      [
        "g",
        {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2"
        },
        [
          [
            "path",
            {
              "d": "M10 3.2A9 9 0 1 0 20.8 14a1 1 0 0 0-1-1H13a2 2 0 0 1-2-2V4a.9.9 0 0 0-1-.8"
            },
            []
          ],
          [
            "path",
            {
              "d": "M15 3.5A9 9 0 0 1 20.5 9H16a1 1 0 0 1-1-1z"
            },
            []
          ]
        ]
      ]
    ]
  },
  "check": {
    "width": 24,
    "height": 24,
    "nodes": [
      [
        "path",
        {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "m5 12l5 5L20 7"
        },
        []
      ]
    ]
  },
  "chevron-down": {
    "width": 24,
    "height": 24,
    "nodes": [
      [
        "path",
        {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "m6 9l6 6l6-6"
        },
        []
      ]
    ]
  },
  "chevron-left": {
    "width": 24,
    "height": 24,
    "nodes": [
      [
        "path",
        {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "m15 6l-6 6l6 6"
        },
        []
      ]
    ]
  },
  "chevron-right": {
    "width": 24,
    "height": 24,
    "nodes": [
      [
        "path",
        {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "m9 6l6 6l-6 6"
        },
        []
      ]
    ]
  },
  "chevron-up": {
    "width": 24,
    "height": 24,
    "nodes": [
      [
        "path",
        {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "m6 15l6-6l6 6"
        },
        []
      ]
    ]
  },
  "chevrons-up-down": {
    "width": 24,
    "height": 24,
    "nodes": [
      [
        "path",
        {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "m8 9l4-4l4 4m0 6l-4 4l-4-4"
        },
        []
      ]
    ]
  },
  "circle": {
    "width": 24,
    "height": 24,
    "nodes": [
      [
        "path",
        {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M3 12a9 9 0 1 0 18 0a9 9 0 1 0-18 0"
        },
        []
      ]
    ]
  },
  "circle-alert": {
    "width": 24,
    "height": 24,
    "nodes": [
      [
        "path",
        {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M3 12a9 9 0 1 0 18 0a9 9 0 1 0-18 0m9-3v4m0 3v.01"
        },
        []
      ]
    ]
  },
  "circle-check": {
    "width": 24,
    "height": 24,
    "nodes": [
      [
        "g",
        {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2"
        },
        [
          [
            "path",
            {
              "d": "M3 12a9 9 0 1 0 18 0a9 9 0 1 0-18 0"
            },
            []
          ],
          [
            "path",
            {
              "d": "m9 12l2 2l4-4"
            },
            []
          ]
        ]
      ]
    ]
  },
  "code-xml": {
    "width": 24,
    "height": 24,
    "nodes": [
      [
        "path",
        {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "m7 8l-4 4l4 4m10-8l4 4l-4 4M14 4l-4 16"
        },
        []
      ]
    ]
  },
  "coffee": {
    "width": 24,
    "height": 24,
    "nodes": [
      [
        "g",
        {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2"
        },
        [
          [
            "path",
            {
              "d": "M3 14c.83.642 2.077 1.017 3.5 1c1.423.017 2.67-.358 3.5-1s2.077-1.017 3.5-1c1.423-.017 2.67.358 3.5 1M8 3a2.4 2.4 0 0 0-1 2a2.4 2.4 0 0 0 1 2m4-4a2.4 2.4 0 0 0-1 2a2.4 2.4 0 0 0 1 2"
            },
            []
          ],
          [
            "path",
            {
              "d": "M3 10h14v5a6 6 0 0 1-6 6H9a6 6 0 0 1-6-6z"
            },
            []
          ],
          [
            "path",
            {
              "d": "M16.746 16.726a3 3 0 1 0 .252-5.555"
            },
            []
          ]
        ]
      ]
    ]
  },
  "command": {
    "width": 24,
    "height": 24,
    "nodes": [
      [
        "path",
        {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M7 9a2 2 0 1 1 2-2v10a2 2 0 1 1-2-2h10a2 2 0 1 1-2 2V7a2 2 0 1 1 2 2z"
        },
        []
      ]
    ]
  },
  "delete": {
    "width": 24,
    "height": 24,
    "nodes": [
      [
        "path",
        {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M4 7h16m-10 4v6m4-6v6M5 7l1 12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2l1-12M9 7V4a1 1 0 0 1 1-1h4a1 1 0 0 1 1 1v3"
        },
        []
      ]
    ]
  },
  "ellipsis": {
    "width": 24,
    "height": 24,
    "nodes": [
      [
        "path",
        {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M4 12a1 1 0 1 0 2 0a1 1 0 1 0-2 0m7 0a1 1 0 1 0 2 0a1 1 0 1 0-2 0m7 0a1 1 0 1 0 2 0a1 1 0 1 0-2 0"
        },
        []
      ]
    ]
  },
  "file": {
    "width": 24,
    "height": 24,
    "nodes": [
      [
        "g",
        {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2"
        },
        [
          [
            "path",
            {
              "d": "M14 3v4a1 1 0 0 0 1 1h4"
            },
            []
          ],
          [
            "path",
            {
              "d": "M17 21H7a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h7l5 5v11a2 2 0 0 1-2 2"
            },
            []
          ]
        ]
      ]
    ]
  },
  "focus": {
    "width": 24,
    "height": 24,
    "nodes": [
      [
        "g",
        {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2"
        },
        [
          [
            "path",
            {
              "fill": "currentColor",
              "d": "M11.5 12a.5.5 0 1 0 1 0a.5.5 0 1 0-1 0"
            },
            []
          ],
          [
            "path",
            {
              "d": "M3 12a9 9 0 1 0 18 0a9 9 0 1 0-18 0"
            },
            []
          ]
        ]
      ]
    ]
  },
  "frame": {
    "width": 24,
    "height": 24,
    "nodes": [
      [
        "path",
        {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M4 7h16M4 17h16M7 4v16M17 4v16"
        },
        []
      ]
    ]
  },
  "gallery-vertical-end": {
    "width": 24,
    "height": 24,
    "nodes": [
      [
        "path",
        {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M4 6a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2zm0 6h16"
        },
        []
      ]
    ]
  },
  "gauge": {
    "width": 24,
    "height": 24,
    "nodes": [
      [
        "g",
        {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2"
        },
        [
          [
            "path",
            {
              "d": "M3 12a9 9 0 1 0 18 0a9 9 0 1 0-18 0"
            },
            []
          ],
          [
            "path",
            {
              "d": "M11 12a1 1 0 1 0 2 0a1 1 0 1 0-2 0m2.41-1.41L16 8m-9 4a5 5 0 0 1 5-5"
            },
            []
          ]
        ]
      ]
    ]
  },
  "ghost": {
    "width": 24,
    "height": 24,
    "nodes": [
      [
        "g",
        {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2"
        },
        [
          [
            "path",
            {
              "d": "M5 11a7 7 0 0 1 14 0v7a1.78 1.78 0 0 1-3.1 1.4a1.65 1.65 0 0 0-2.6 0a1.65 1.65 0 0 1-2.6 0a1.65 1.65 0 0 0-2.6 0A1.78 1.78 0 0 1 5 18zm5-1h.01M14 10h.01"
            },
            []
          ],
          [
            "path",
            {
              "d": "M10 14a3.5 3.5 0 0 0 4 0"
            },
            []
          ]
        ]
      ]
    ]
  },
  "grip-vertical": {
    "width": 24,
    "height": 24,
    "nodes": [
      [
        "path",
        {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M8 5a1 1 0 1 0 2 0a1 1 0 1 0-2 0m0 7a1 1 0 1 0 2 0a1 1 0 1 0-2 0m0 7a1 1 0 1 0 2 0a1 1 0 1 0-2 0m6-14a1 1 0 1 0 2 0a1 1 0 1 0-2 0m0 7a1 1 0 1 0 2 0a1 1 0 1 0-2 0m0 7a1 1 0 1 0 2 0a1 1 0 1 0-2 0"
        },
        []
      ]
    ]
  },
  "group": {
    "width": 24,
    "height": 24,
    "nodes": [
      [
        "path",
        {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M10 13a2 2 0 1 0 4 0a2 2 0 0 0-4 0m-2 8v-1a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v1M15 5a2 2 0 1 0 4 0a2 2 0 0 0-4 0m2 5h2a2 2 0 0 1 2 2v1M5 5a2 2 0 1 0 4 0a2 2 0 0 0-4 0m-2 8v-1a2 2 0 0 1 2-2h2"
        },
        []
      ]
    ]
  },
  "house": {
    "width": 24,
    "height": 24,
    "nodes": [
      [
        "g",
        {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2"
        },
        [
          [
            "path",
            {
              "d": "M5 12H3l9-9l9 9h-2M5 12v7a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2v-7"
            },
            []
          ],
          [
            "path",
            {
              "d": "M9 21v-6a2 2 0 0 1 2-2h2a2 2 0 0 1 2 2v6"
            },
            []
          ]
        ]
      ]
    ]
  },
  "image": {
    "width": 24,
    "height": 24,
    "nodes": [
      [
        "g",
        {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2"
        },
        [
          [
            "path",
            {
              "d": "M15 8h.01M3 6a3 3 0 0 1 3-3h12a3 3 0 0 1 3 3v12a3 3 0 0 1-3 3H6a3 3 0 0 1-3-3z"
            },
            []
          ],
          [
            "path",
            {
              "d": "m3 16l5-5c.928-.893 2.072-.893 3 0l5 5"
            },
            []
          ],
          [
            "path",
            {
              "d": "m14 14l1-1c.928-.893 2.072-.893 3 0l3 3"
            },
            []
          ]
        ]
      ]
    ]
  },
  "inbox": {
    "width": 24,
    "height": 24,
    "nodes": [
      [
        "g",
        {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2"
        },
        [
          [
            "path",
            {
              "d": "M4 6a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2z"
            },
            []
          ],
          [
            "path",
            {
              "d": "M4 13h3l3 3h4l3-3h3"
            },
            []
          ]
        ]
      ]
    ]
  },
  "info": {
    "width": 24,
    "height": 24,
    "nodes": [
      [
        "g",
        {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2"
        },
        [
          [
            "path",
            {
              "d": "M3 12a9 9 0 1 0 18 0a9 9 0 0 0-18 0m9-3h.01"
            },
            []
          ],
          [
            "path",
            {
              "d": "M11 12h1v4h1"
            },
            []
          ]
        ]
      ]
    ]
  },
  "life-buoy": {
    "width": 24,
    "height": 24,
    "nodes": [
      [
        "g",
        {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2"
        },
        [
          [
            "path",
            {
              "d": "M8 12a4 4 0 1 0 8 0a4 4 0 1 0-8 0"
            },
            []
          ],
          [
            "path",
            {
              "d": "M3 12a9 9 0 1 0 18 0a9 9 0 1 0-18 0m12 3l3.35 3.35M9 15l-3.35 3.35m0-12.7L9 9m9.35-3.35L15 9"
            },
            []
          ]
        ]
      ]
    ]
  },
  "link": {
    "width": 24,
    "height": 24,
    "nodes": [
      [
        "path",
        {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "m9 15l6-6m-4-3l.463-.536a5 5 0 0 1 7.071 7.072L18 13m-5 5l-.397.534a5.07 5.07 0 0 1-7.127 0a4.97 4.97 0 0 1 0-7.071L6 11"
        },
        []
      ]
    ]
  },
  "list": {
    "width": 24,
    "height": 24,
    "nodes": [
      [
        "path",
        {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M9 6h11M9 12h11M9 18h11M5 6v.01M5 12v.01M5 18v.01"
        },
        []
      ]
    ]
  },
  "loader-circle": {
    "width": 24,
    "height": 24,
    "nodes": [
      [
        "path",
        {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M12 3a9 9 0 1 0 9 9"
        },
        []
      ]
    ]
  },
  "lock": {
    "width": 24,
    "height": 24,
    "nodes": [
      [
        "g",
        {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2"
        },
        [
          [
            "path",
            {
              "d": "M5 13a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2v6a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2z"
            },
            []
          ],
          [
            "path",
            {
              "d": "M11 16a1 1 0 1 0 2 0a1 1 0 0 0-2 0m-3-5V7a4 4 0 1 1 8 0v4"
            },
            []
          ]
        ]
      ]
    ]
  },
  "lock-keyhole": {
    "width": 24,
    "height": 24,
    "nodes": [
      [
        "g",
        {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2"
        },
        [
          [
            "path",
            {
              "d": "M5 13a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2v6a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2z"
            },
            []
          ],
          [
            "path",
            {
              "d": "M11 16a1 1 0 1 0 2 0a1 1 0 0 0-2 0m-3-5V7a4 4 0 1 1 8 0v4"
            },
            []
          ]
        ]
      ]
    ]
  },
  "log-out": {
    "width": 24,
    "height": 24,
    "nodes": [
      [
        "g",
        {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2"
        },
        [
          [
            "path",
            {
              "d": "M14 8V6a2 2 0 0 0-2-2H5a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h7a2 2 0 0 0 2-2v-2"
            },
            []
          ],
          [
            "path",
            {
              "d": "M9 12h12l-3-3m0 6l3-3"
            },
            []
          ]
        ]
      ]
    ]
  },
  "map": {
    "width": 24,
    "height": 24,
    "nodes": [
      [
        "path",
        {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "m3 7l6-3l6 3l6-3v13l-6 3l-6-3l-6 3zm6-3v13m6-10v13"
        },
        []
      ]
    ]
  },
  "minus": {
    "width": 24,
    "height": 24,
    "nodes": [
      [
        "path",
        {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M5 12h14"
        },
        []
      ]
    ]
  },
  "octagon-x": {
    "width": 24,
    "height": 24,
    "nodes": [
      [
        "path",
        {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "m12.802 2.165l5.575 2.389c.48.206.863.589 1.07 1.07l2.388 5.574c.22.512.22 1.092 0 1.604l-2.389 5.575c-.206.48-.589.863-1.07 1.07l-5.574 2.388c-.512.22-1.092.22-1.604 0l-5.575-2.389a2.04 2.04 0 0 1-1.07-1.07l-2.388-5.574a2.04 2.04 0 0 1 0-1.604l2.389-5.575c.206-.48.589-.863 1.07-1.07l5.574-2.388a2.04 2.04 0 0 1 1.604 0M12 8v4m0 4h.01"
        },
        []
      ]
    ]
  },
  "panel-left": {
    "width": 24,
    "height": 24,
    "nodes": [
      [
        "path",
        {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M4 6a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2zm5-2v16"
        },
        []
      ]
    ]
  },
  "plus": {
    "width": 24,
    "height": 24,
    "nodes": [
      [
        "path",
        {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M12 5v14m-7-7h14"
        },
        []
      ]
    ]
  },
  "radar": {
    "width": 24,
    "height": 24,
    "nodes": [
      [
        "g",
        {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2"
        },
        [
          [
            "path",
            {
              "d": "M21 12h-8a1 1 0 1 0-1 1v8a9 9 0 0 0 9-9"
            },
            []
          ],
          [
            "path",
            {
              "d": "M16 9a5 5 0 1 0-7 7"
            },
            []
          ],
          [
            "path",
            {
              "d": "M20.486 9A9 9 0 1 0 9.004 20.495"
            },
            []
          ]
        ]
      ]
    ]
  },
  "radio": {
    "width": 24,
    "height": 24,
    "nodes": [
      [
        "path",
        {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M14 3L4.629 6.749A1 1 0 0 0 4 7.677V19a1 1 0 0 0 1 1h14a1 1 0 0 0 1-1V8a1 1 0 0 0-1-1H4.5M4 12h16M7 12v-2m10 6v.01M13 16v.01"
        },
        []
      ]
    ]
  },
  "radius": {
    "width": 24,
    "height": 24,
    "nodes": [
      [
        "path",
        {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M4 12V8a4 4 0 0 1 4-4h4m4 0v.01M20 4v.01M20 8v.01M20 12v.01M4 16v.01M20 16v.01M4 20v.01M8 20v.01m4-.01v.01m4-.01v.01m4-.01v.01"
        },
        []
      ]
    ]
  },
  "refresh-cw": {
    "width": 24,
    "height": 24,
    "nodes": [
      [
        "path",
        {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M20 11A8.1 8.1 0 0 0 4.5 9M4 5v4h4m-4 4a8.1 8.1 0 0 0 15.5 2m.5 4v-4h-4"
        },
        []
      ]
    ]
  },
  "repeat": {
    "width": 24,
    "height": 24,
    "nodes": [
      [
        "path",
        {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M4 12V9a3 3 0 0 1 3-3h13m-3-3l3 3l-3 3m3 3v3a3 3 0 0 1-3 3H4m3 3l-3-3l3-3"
        },
        []
      ]
    ]
  },
  "rose": {
    "width": 24,
    "height": 24,
    "nodes": [
      [
        "g",
        {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2"
        },
        [
          [
            "path",
            {
              "d": "M9 12a3 3 0 1 0 6 0a3 3 0 1 0-6 0"
            },
            []
          ],
          [
            "path",
            {
              "d": "M12 2a3 3 0 0 1 3 3q0 .843-.776 2.64L13.5 9l1.76-1.893q.748-.899 1.27-1.205a2.97 2.97 0 0 1 4.07 1.099a3.01 3.01 0 0 1-1.09 4.098q-.561.326-1.846.535L15 12l2.4.326c1 .145 1.698.337 2.11.576A3.01 3.01 0 0 1 20.6 17a2.97 2.97 0 0 1-4.07 1.098q-.522-.303-1.27-1.205L13.5 15l.724 1.36q.775 1.799.776 2.64a3 3 0 0 1-6 0q0-.843.776-2.64L10.5 15l-1.76 1.893q-.748.9-1.27 1.205A2.97 2.97 0 0 1 3.4 17a3.01 3.01 0 0 1 1.09-4.098q.561-.326 1.846-.536L9 12l-2.4-.325c-1-.145-1.698-.337-2.11-.576A3.01 3.01 0 0 1 3.4 7a2.97 2.97 0 0 1 4.07-1.099q.522.304 1.27 1.205L10.5 9Q9 5.562 9 5a3 3 0 0 1 3-3"
            },
            []
          ]
        ]
      ]
    ]
  },
  "search": {
    "width": 24,
    "height": 24,
    "nodes": [
      [
        "path",
        {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M3 10a7 7 0 1 0 14 0a7 7 0 1 0-14 0m18 11l-6-6"
        },
        []
      ]
    ]
  },
  "send": {
    "width": 24,
    "height": 24,
    "nodes": [
      [
        "path",
        {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M10 14L21 3m0 0l-6.5 18a.55.55 0 0 1-1 0L10 14l-7-3.5a.55.55 0 0 1 0-1z"
        },
        []
      ]
    ]
  },
  "settings-2": {
    "width": 24,
    "height": 24,
    "nodes": [
      [
        "g",
        {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2"
        },
        [
          [
            "path",
            {
              "d": "M19.875 6.27A2.23 2.23 0 0 1 21 8.218v7.284c0 .809-.443 1.555-1.158 1.948l-6.75 4.27a2.27 2.27 0 0 1-2.184 0l-6.75-4.27A2.23 2.23 0 0 1 3 15.502V8.217c0-.809.443-1.554 1.158-1.947l6.75-3.98a2.33 2.33 0 0 1 2.25 0l6.75 3.98z"
            },
            []
          ],
          [
            "path",
            {
              "d": "M9 12a3 3 0 1 0 6 0a3 3 0 1 0-6 0"
            },
            []
          ]
        ]
      ]
    ]
  },
  "share": {
    "width": 24,
    "height": 24,
    "nodes": [
      [
        "path",
        {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M3 12a3 3 0 1 0 6 0a3 3 0 1 0-6 0m12-6a3 3 0 1 0 6 0a3 3 0 1 0-6 0m0 12a3 3 0 1 0 6 0a3 3 0 1 0-6 0m-6.3-7.3l6.6-3.4m-6.6 6l6.6 3.4"
        },
        []
      ]
    ]
  },
  "shopping-cart": {
    "width": 24,
    "height": 24,
    "nodes": [
      [
        "g",
        {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2"
        },
        [
          [
            "path",
            {
              "d": "M4 19a2 2 0 1 0 4 0a2 2 0 1 0-4 0m11 0a2 2 0 1 0 4 0a2 2 0 1 0-4 0"
            },
            []
          ],
          [
            "path",
            {
              "d": "M17 17H6V3H4"
            },
            []
          ],
          [
            "path",
            {
              "d": "m6 5l14 1l-1 7H6"
            },
            []
          ]
        ]
      ]
    ]
  },
  "sparkles": {
    "width": 24,
    "height": 24,
    "nodes": [
      [
        "path",
        {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M16 18a2 2 0 0 1 2 2a2 2 0 0 1 2-2a2 2 0 0 1-2-2a2 2 0 0 1-2 2m0-12a2 2 0 0 1 2 2a2 2 0 0 1 2-2a2 2 0 0 1-2-2a2 2 0 0 1-2 2M9 18a6 6 0 0 1 6-6a6 6 0 0 1-6-6a6 6 0 0 1-6 6a6 6 0 0 1 6 6"
        },
        []
      ]
    ]
  },
  "square-terminal": {
    "width": 24,
    "height": 24,
    "nodes": [
      [
        "g",
        {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2"
        },
        [
          [
            "path",
            {
              "d": "m8 9l3 3l-3 3m5 0h3"
            },
            []
          ],
          [
            "path",
            {
              "d": "M3 6a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"
            },
            []
          ]
        ]
      ]
    ]
  },
  "stone": {
    "width": 24,
    "height": 24,
    "nodes": [
      [
        "g",
        {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2"
        },
        [
          [
            "path",
            {
              "d": "M3 20h18L14.079 5.388a2.3 2.3 0 0 0-4.158 0z"
            },
            []
          ],
          [
            "path",
            {
              "d": "m7.5 11l2 2.5L12 11l2 3l2.5-2"
            },
            []
          ]
        ]
      ]
    ]
  },
  "sun": {
    "width": 24,
    "height": 24,
    "nodes": [
      [
        "path",
        {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M8 12a4 4 0 1 0 8 0a4 4 0 1 0-8 0m-5 0h1m8-9v1m8 8h1m-9 8v1M5.6 5.6l.7.7m12.1-.7l-.7.7m0 11.4l.7.7m-12.1-.7l-.7.7"
        },
        []
      ]
    ]
  },
  "table": {
    "width": 24,
    "height": 24,
    "nodes": [
      [
        "path",
        {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M3 5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2zm0 5h18M10 3v18"
        },
        []
      ]
    ]
  },
  "thermometer": {
    "width": 24,
    "height": 24,
    "nodes": [
      [
        "path",
        {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M19 5a2.83 2.83 0 0 1 0 4l-8 8H7v-4l8-8a2.83 2.83 0 0 1 4 0m-3 2l-1.5-1.5M13 10l-1.5-1.5M10 13l-1.5-1.5M7 17l-3 3"
        },
        []
      ]
    ]
  },
  "timer": {
    "width": 24,
    "height": 24,
    "nodes": [
      [
        "g",
        {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2"
        },
        [
          [
            "path",
            {
              "d": "M3 12a9 9 0 1 0 18 0a9 9 0 0 0-18 0"
            },
            []
          ],
          [
            "path",
            {
              "d": "M12 7v5l3 3"
            },
            []
          ]
        ]
      ]
    ]
  },
  "trash-2": {
    "width": 24,
    "height": 24,
    "nodes": [
      [
        "path",
        {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M4 7h16m-10 4v6m4-6v6M5 7l1 12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2l1-12M9 7V4a1 1 0 0 1 1-1h4a1 1 0 0 1 1 1v3"
        },
        []
      ]
    ]
  },
  "trending-up": {
    "width": 24,
    "height": 24,
    "nodes": [
      [
        "g",
        {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2"
        },
        [
          [
            "path",
            {
              "d": "m3 17l6-6l4 4l8-8"
            },
            []
          ],
          [
            "path",
            {
              "d": "M14 7h7v7"
            },
            []
          ]
        ]
      ]
    ]
  },
  "triangle-alert": {
    "width": 24,
    "height": 24,
    "nodes": [
      [
        "path",
        {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M12 9v4m-1.637-9.409L2.257 17.125a1.914 1.914 0 0 0 1.636 2.871h16.214a1.914 1.914 0 0 0 1.636-2.87L13.637 3.59a1.914 1.914 0 0 0-3.274 0M12 16h.01"
        },
        []
      ]
    ]
  },
  "tv": {
    "width": 24,
    "height": 24,
    "nodes": [
      [
        "path",
        {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M3 9a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2zm13-6l-4 4l-4-4"
        },
        []
      ]
    ]
  },
  "view": {
    "width": 24,
    "height": 24,
    "nodes": [
      [
        "g",
        {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2"
        },
        [
          [
            "path",
            {
              "d": "M10 12a2 2 0 1 0 4 0a2 2 0 0 0-4 0"
            },
            []
          ],
          [
            "path",
            {
              "d": "M21 12q-3.6 6-9 6t-9-6q3.6-6 9-6t9 6"
            },
            []
          ]
        ]
      ]
    ]
  },
  "volume": {
    "width": 24,
    "height": 24,
    "nodes": [
      [
        "path",
        {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M15 8a5 5 0 0 1 0 8m2.7-11a9 9 0 0 1 0 14M6 15H4a1 1 0 0 1-1-1v-4a1 1 0 0 1 1-1h2l3.5-4.5A.8.8 0 0 1 11 5v14a.8.8 0 0 1-1.5.5z"
        },
        []
      ]
    ]
  },
  "volume-2": {
    "width": 24,
    "height": 24,
    "nodes": [
      [
        "path",
        {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M15 8a5 5 0 0 1 0 8m-9-1H4a1 1 0 0 1-1-1v-4a1 1 0 0 1 1-1h2l3.5-4.5A.8.8 0 0 1 11 5v14a.8.8 0 0 1-1.5.5z"
        },
        []
      ]
    ]
  },
  "wallet": {
    "width": 24,
    "height": 24,
    "nodes": [
      [
        "g",
        {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2"
        },
        [
          [
            "path",
            {
              "d": "M17 8V5a1 1 0 0 0-1-1H6a2 2 0 0 0 0 4h12a1 1 0 0 1 1 1v3m0 4v3a1 1 0 0 1-1 1H6a2 2 0 0 1-2-2V6"
            },
            []
          ],
          [
            "path",
            {
              "d": "M20 12v4h-4a2 2 0 0 1 0-4z"
            },
            []
          ]
        ]
      ]
    ]
  },
  "x": {
    "width": 24,
    "height": 24,
    "nodes": [
      [
        "path",
        {
          "fill": "none",
          "stroke": "currentColor",
          "stroke-linecap": "round",
          "stroke-linejoin": "round",
          "stroke-width": "2",
          "d": "M18 6L6 18M6 6l12 12"
        },
        []
      ]
    ]
  }
} as const;
