import type { EChartsOption } from 'echarts/types/dist/shared';
import { Schema as S } from 'effect';
import type { HtmlBuilder } from 'foldkit/html';
import { m } from 'foldkit/message';
import { definePreviewProgram } from '@/docs/components/pages/authored-page';
import { chartData, chartHostId } from '@/docs/components/pages/chart/shared';
import * as Chart from '@/ui/chart';
import * as Table from '@/ui/table';

Chart.registerChart(chartHostId, (theme, variant): EChartsOption => ({ grid: Chart.compactGrid(), series: [{ data: variant === 'quarter' ? [186, 305, 237, 314] : [186, 305, 237, 273, 209, 314], itemStyle: { color: theme.chart2 }, name: 'Revenue', type: 'bar' }], tooltip: Chart.shadcnTooltip(theme), xAxis: Chart.categoryAxis(theme, variant === 'quarter' ? ['Q1', 'Q2', 'Q3', 'Q4'] : ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun'], { boundaryGap: true }), yAxis: Chart.valueAxis(theme, { showLabels: true }) }));
const Changed = m('ChangedChartRange', { variant: S.Literals(['month', 'quarter']) }); const Message = S.Union([Chart.ChartMessage, Changed]); type Message = typeof Message.Type; const Model = S.Struct({ _docsPage: S.Literal('chart'), variant: S.Literals(['month', 'quarter']) }); type Model = typeof Model.Type;
const table = <Msg>(h: HtmlBuilder<Msg>) => Table.table({ children: [Table.tableCaption({ children: ['Revenue values shown in the chart.'] }, h), Table.tableHeader({ children: [Table.tableRow({ children: [Table.tableHead({ children: ['Period'] }, h), Table.tableHead({ children: ['Revenue'] }, h)] }, h)] }, h), Table.tableBody({ children: [['Jan', '$186k'], ['Feb', '$305k'], ['Mar', '$237k']].map(([period, value]) => Table.tableRow({ children: [Table.tableHead({ scope: 'row', children: [period ?? ''] }, h), Table.tableCell({ children: [value ?? ''] }, h)] }, h)) }, h)] }, h);
export const chartTailwindPreviewProgram = definePreviewProgram<Model, Message>({ Model, Message, init: () => ({ _docsPage: 'chart', variant: 'month' }), update: (model, message) => message._tag === 'ChangedChartRange' ? [{ ...model, variant: message.variant }, [Chart.SyncChart({ hostId: chartHostId, variant: message.variant })]] : [model, []], view: (index, model, h) => index === 0 ? Chart.barChart({ class: 'max-w-xl', data: chartData }, h) : index === 1 ? h.div([h.Class('w-full max-w-xl space-y-4')], [Chart.areaChart({ data: chartData.map(x => x.value) }, h), Chart.chartLegend({ config: { visitors: { label: 'Visitors', color: 'var(--chart-2)' } } }, h)]) : index === 2 ? h.div([h.Class('w-full max-w-xl space-y-3')], [h.button([h.Type('button'), h.OnClick(Changed({ variant: model.variant === 'month' ? 'quarter' : 'month' })), h.Class('rounded-md border px-3 py-2 text-sm')], [model.variant === 'month' ? 'Show quarters' : 'Show months']), Chart.eChart({ accessibleAlternative: table(h), ariaLabel: 'Revenue by period', hostId: chartHostId, toMessage: message => message, variant: model.variant }, h)]) : h.div([h.Class('grid w-full max-w-xl gap-3')], [Chart.eChart({ accessibleAlternative: h.p([], ['Revenue data is loading.']), ariaLabel: 'Loading revenue', hostId: `${chartHostId}-loading`, state: 'loading', toMessage: message => message }, h), Chart.eChart({ accessibleAlternative: h.p([], ['No revenue records are available.']), ariaLabel: 'Empty revenue', hostId: `${chartHostId}-empty`, state: 'empty', toMessage: message => message }, h), Chart.eChart({ accessibleAlternative: h.p([], ['Revenue service is unavailable.']), ariaLabel: 'Revenue error', hostId: `${chartHostId}-error`, state: 'error', statusText: 'Revenue could not be loaded.', toMessage: message => message }, h)]) });
