import * as stylex from '@stylexjs/stylex'

/** Semantic tokens shared by the data-rich and navigation component families. */
export const complexTokens = stylex.defineVars({
  sidebar: 'var(--sidebar)',
  sidebarForeground: 'var(--sidebar-foreground)',
  sidebarPrimary: 'var(--sidebar-primary)',
  sidebarPrimaryForeground: 'var(--sidebar-primary-foreground)',
  sidebarAccent: 'var(--sidebar-accent)',
  sidebarAccentForeground: 'var(--sidebar-accent-foreground)',
  sidebarBorder: 'var(--sidebar-border)',
  sidebarRing: 'var(--sidebar-ring)',
  chart1: 'var(--chart-1)',
  chart2: 'var(--chart-2)',
  chart3: 'var(--chart-3)',
  chart4: 'var(--chart-4)',
  chart5: 'var(--chart-5)',
  mutedSurface: 'color-mix(in oklab, var(--muted) 50%, transparent)',
  opaqueMutedSurface:
    'color-mix(in oklab, var(--muted) 50%, var(--background))',
  accentSurface: 'color-mix(in oklab, var(--accent) 50%, transparent)',
  opaqueAccentSurface:
    'color-mix(in oklab, var(--accent) 50%, var(--background))',
  focusOutline: '1px solid var(--ring)',
  resizeShadow: '0 0 0 1px var(--ring)',
  smallRadius: '2px',
  overlaySurface: 'color-mix(in oklab, var(--foreground) 50%, transparent)',
  transparent: 'transparent',
  sidebarEdgeRing: '0 0 0 1px var(--sidebar-border)',
  sidebarAccentRing: '0 0 0 1px var(--sidebar-accent)',
  sidebarForegroundDim:
    'color-mix(in oklab, var(--sidebar-foreground) 70%, transparent)',
  chart1Soft10: 'color-mix(in oklab, var(--chart-1) 10%, transparent)',
  chart2Soft10: 'color-mix(in oklab, var(--chart-2) 10%, transparent)',
  chart3Soft10: 'color-mix(in oklab, var(--chart-3) 10%, transparent)',
  chart2Soft15: 'color-mix(in oklab, var(--chart-2) 15%, transparent)',
  chart3Soft15: 'color-mix(in oklab, var(--chart-3) 15%, transparent)',
  chart4Soft15: 'color-mix(in oklab, var(--chart-4) 15%, transparent)',
  chart2Soft25: 'color-mix(in oklab, var(--chart-2) 25%, transparent)',
  destructiveSoft15: 'color-mix(in oklab, var(--destructive) 15%, transparent)',
  chart2Soft20: 'color-mix(in oklab, var(--chart-2) 20%, transparent)',
  chart4Soft20: 'color-mix(in oklab, var(--chart-4) 20%, transparent)',
  destructiveSoft20: 'color-mix(in oklab, var(--destructive) 20%, transparent)',
  chart4Soft5: 'color-mix(in srgb, var(--chart-4) 5%, transparent)',
  destructiveSoft6: 'color-mix(in srgb, var(--destructive) 6%, transparent)',
})
