import * as stylex from '@stylexjs/stylex'

export const foundationTokens = stylex.defineVars({
  muted: 'var(--muted)',
  popover: 'var(--popover)',
  popoverForeground: 'var(--popover-foreground)',
  destructiveSoft: 'color-mix(in oklab, var(--destructive) 10%, transparent)',
  destructiveMuted: 'color-mix(in oklab, var(--destructive) 80%, transparent)',
  primarySoft: 'color-mix(in oklab, var(--primary) 10%, transparent)',
  foregroundMuted: 'color-mix(in oklab, var(--foreground) 60%, transparent)',
  foregroundSoft: 'color-mix(in oklab, var(--foreground) 10%, transparent)',
  ringSoft: 'color-mix(in oklab, var(--ring) 50%, transparent)',
  destructiveRingSoft: 'color-mix(in oklab, var(--destructive) 20%, transparent)',
  inputDark: 'color-mix(in oklab, var(--input) 30%, transparent)',
  mutedSoft: 'color-mix(in oklab, var(--muted) 50%, transparent)',
  shadowXs: '0 1px 2px rgb(0 0 0 / 0.05)',
  shadowNone: 'none',
  checkboxRadius: '4px',
  radiusSm: 'calc(var(--radius) - 4px)',
  radiusMd: 'calc(var(--radius) - 2px)',
  radiusLg: 'var(--radius)',
  radiusXl: 'calc(var(--radius) + 4px)',
  radiusBase: '4px',
  radiusNested: 'calc(var(--radius) - 5px)',
  radius2xl: '1rem',
  radiusMdCap8: 'min(var(--radius-md), 8px)',
  radiusMdCap10: 'min(var(--radius-md), 10px)',
  radiusFull: '9999px',
  transparent: 'transparent',
  leadingNormal: '1.5',
  white: 'rgb(255 255 255)',
  shadowSm: '0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)',
  shadowMd: '0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)',
  shadowXl: '0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)',
  ringShadow1: '0 0 0 1px color-mix(in oklab, var(--ring) 50%, transparent)',
  cardRing3: '0 0 0 3px var(--card)',
  ringShadow4: '0 0 0 4px color-mix(in oklab, var(--ring) 50%, transparent)',
  overlay40: 'rgb(0 0 0 / 0.4)',
  overlay50: 'rgb(0 0 0 / 0.5)',
  mutedForeground50: 'color-mix(in oklab, var(--muted-foreground) 50%, transparent)',
  mutedForeground60: 'color-mix(in oklab, var(--muted-foreground) 60%, transparent)',
  foregroundFaint: 'color-mix(in oklab, var(--foreground) 5%, transparent)',
  primaryFaint: 'color-mix(in oklab, var(--primary) 5%, transparent)',
  primarySoft20: 'color-mix(in oklab, var(--primary) 20%, transparent)',
  destructiveFaint: 'color-mix(in oklab, var(--destructive) 5%, transparent)',
  destructiveEdge40: 'color-mix(in oklab, var(--destructive) 40%, transparent)',
  avatarBadgeSuccess: 'oklch(0.627 0.194 149.214)',
  nativeOptionSurface: 'Canvas',
  nativeOptionInk: 'CanvasText',
})

