import * as stylex from '@stylexjs/stylex'
import type { Html, HtmlBuilder } from 'foldkit/html'
import type { ComponentLayoutStyle } from './contracts'
import { foundationTokens } from './foundations-tokens.stylex'
import { className } from './style'
import { tokens } from './tokens.stylex'
import { interactionTokens } from './interaction-tokens.stylex.const'
const styles=stylex.create({root:{alignItems:'center',display:'inline-flex',position:'relative'},input:{inset:0, cursor:interactionTokens.cursorText, opacity:0, position:'absolute', zIndex:10, height:'100%', width:'100%',},group:{alignItems:'center',display:'flex'},slot:{borderColor:tokens.input, borderStyle:'solid', borderWidth:1, alignItems:'center', boxShadow:foundationTokens.shadowXs, display:'flex', fontSize:'0.875rem', justifyContent:'center', position:'relative', height:'2.25rem', width:'2.25rem',},active:{borderColor:tokens.ring,boxShadow:tokens.focusRingShadow},disabled:{opacity:.5},caretWrap:{inset:0, alignItems:'center', display:'flex', justifyContent:'center', pointerEvents:'none', position:'absolute',},caret:{animationDuration:interactionTokens.motionLoopFast,animationIterationCount:'infinite',animationName:stylex.keyframes({'0%, 100%':{opacity:1},'50%':{opacity:0}}),backgroundColor:tokens.foreground,height:'1rem',width:'1px'},contents:{display:'contents'},separator:{color:tokens.mutedForeground,paddingInline:'0.5rem'}})
export type InputOtpProps<Msg>=Readonly<{id:string;value:string;onInput:(value:string)=>Msg;length?:number;name?:string;ariaLabel?:string;isDisabled?:boolean;isInvalid?:boolean;layoutStyle?:ComponentLayoutStyle;groupLayoutStyle?:ComponentLayoutStyle;pattern?:RegExp;inputMode?:'numeric'|'text'|'tel'|'decimal'|'email'|'url'|'search';slotLayoutStyle?:ComponentLayoutStyle;separator?:(index:number)=>Html}>
const normalize=(value:string,length:number,pattern:RegExp):string=>Array.from(value).filter(character=>{pattern.lastIndex=0;return pattern.test(character)}).slice(0,length).join('')
export const inputOtp=<Msg>(p:InputOtpProps<Msg>,h:HtmlBuilder<Msg>):Html=>{const length=p.length??6,pattern=p.pattern??/[0-9]/,value=normalize(p.value,length,pattern);return h.div([h.DataAttribute('slot','input-otp'),h.Class(className(styles.root,p.layoutStyle))],[h.input([h.Id(p.id),h.Type('text'),h.Value(value),h.InputMode(p.inputMode??'numeric'),h.Pattern(pattern.source),h.Maxlength(length),h.Autocomplete('one-time-code'),h.Spellcheck(false),h.AriaLabel(p.ariaLabel??'One-time password'),h.AriaInvalid(p.isInvalid??false),h.Disabled(p.isDisabled??false),...(p.name===undefined?[]:[h.Name(p.name)]),h.OnInput(next=>p.onInput(normalize(next,length,pattern))),h.Class(className(styles.input))]),h.div([h.DataAttribute('slot','input-otp-group'),h.AriaHidden(true),h.Class(className(styles.group,p.groupLayoutStyle))],Array.from({length},(_,index)=>{const character=value[index],isActive=value.length===index;const slot=h.div([h.DataAttribute('slot','input-otp-slot'),h.DataAttribute('active',String(isActive)),h.Class(className(styles.slot,isActive&&styles.active,p.isDisabled&&styles.disabled,p.slotLayoutStyle))],[character??'',...(isActive?[h.div([h.Class(className(styles.caretWrap))],[h.div([h.Class(className(styles.caret))],[])])]:[])]);const separator=p.separator?.(index);return separator===undefined||index===length-1?slot:h.div([h.Class(className(styles.contents))],[slot,separator])}))])}
export const inputOtpSeparator=<Msg>(h:HtmlBuilder<Msg>):Html=>h.div([h.Role('separator'),h.DataAttribute('slot','input-otp-separator'),h.Class(className(styles.separator))],['Â·'])


