import * as stylex from '@stylexjs/stylex'
import { Option } from 'effect'
import type { Html, HtmlBuilder } from 'foldkit/html'
import { RadioGroup as RadioGroupPrimitive } from '@foldkit/ui'
import * as Icon from '@/lib/icon'
import type { ComponentLayoutStyle } from './contracts'
import { foundationTokens } from './foundations-tokens.stylex'
import { className } from './style'
import { tokens } from './tokens.stylex'
import { interactionTokens } from './interaction-tokens.stylex.const'
const styles=stylex.create({group:{gap:'0.75rem', display:'grid',},groupColumns2:{gridTemplateColumns:{default:'minmax(0, 1fr)','@media (min-width: 768px)':'repeat(2, minmax(0, 1fr))'}},row:{gap:'0.5rem', alignItems:'start', display:'flex',},item:{borderColor:{default:tokens.input,':focus-visible':tokens.ring}, borderRadius:'50%', borderStyle:'solid', borderWidth:1, placeContent:'center', alignItems:'center', aspectRatio:'1', backgroundColor:foundationTokens.transparent, boxShadow:{default:foundationTokens.shadowXs,':focus-visible':tokens.focusRingShadow}, color:tokens.primary, display:'grid', flexShrink:0, outlineStyle:'none', height:'1rem', width:'1rem',},disabled:{cursor:interactionTokens.cursorDisabled,opacity:.5},indicator:{alignItems:'center',display:'flex',justifyContent:'center',position:'relative'},dot:{borderRadius:'50%', backgroundColor:tokens.primary, height:'0.5rem', width:'0.5rem',},text:{gap:'0.375rem', display:'grid',},label:{fontSize:'0.875rem',fontWeight:500,lineHeight:1,userSelect:'none'},description:{color:tokens.mutedForeground,fontSize:'0.875rem'}})
export type RadioGroupOption=Readonly<{value:string;label:string;description?:string}>
export type RadioGroupProps<Msg>=Readonly<{model:Model;toParentMessage:(message:Message)=>Msg;selectedValue:Option.Option<string>;ariaLabel:string;options:ReadonlyArray<RadioGroupOption>;columns?:1|2;isDisabled?:boolean;name?:string;orientation?:RadioGroupPrimitive.Orientation;layoutStyle?:ComponentLayoutStyle}>
export const Model=RadioGroupPrimitive.Model;export type Model=typeof Model.Type;export const Message=RadioGroupPrimitive.Message;export type Message=typeof Message.Type;export type OutMessage=RadioGroupPrimitive.OutMessage<string>;export const init=RadioGroupPrimitive.init;const StringRadioGroup=RadioGroupPrimitive.create<string>();export const update=StringRadioGroup.update
export const radioGroup=<Msg>(p:RadioGroupProps<Msg>,h:HtmlBuilder<Msg>):Html=>h.submodel({slotId:p.model.id,model:p.model,view:StringRadioGroup.view,viewInputs:{selectedValue:p.selectedValue,options:p.options.map(o=>o.value),ariaLabel:p.ariaLabel,isDisabled:p.isDisabled??false,...(p.name===undefined?{}:{name:p.name}),...(p.orientation===undefined?{}:{orientation:p.orientation}),toView:({group,options,hiddenInput})=>h.div([...group,h.DataAttribute('slot','radio-group'),h.Class(className(styles.group,p.columns===2&&styles.groupColumns2,p.layoutStyle))],[...options.map(option=>{const content=p.options[option.index];if(content===undefined)return h.span([],[]);const selected=Option.getOrUndefined(p.selectedValue)===content.value;return h.div([h.Class(className(styles.row))],[h.button([...option.option,h.Type('button'),h.DataAttribute('slot','radio-group-item'),h.Class(className(styles.item,p.isDisabled&&styles.disabled))],[h.span([h.DataAttribute('slot','radio-group-indicator'),h.Class(className(styles.indicator))],selected?[Icon.circleIcon({class:className(styles.dot)},h)]:[])]),h.div([h.Class(className(styles.text))],[h.label([...option.label,h.Class(className(styles.label))],[content.label]),...(content.description===undefined?[]:[h.p([...option.description,h.Class(className(styles.description))],[content.description])])])])}),...(p.name===undefined?[]:[h.input([...hiddenInput])])])},toParentMessage:p.toParentMessage})


