import * as stylex from '@stylexjs/stylex'
import type { Html, HtmlBuilder } from 'foldkit/html'
import { Button as ButtonPrimitive } from '@foldkit/ui'
import type { ComponentLayoutStyle } from './contracts'
import { foundationTokens } from './foundations-tokens.stylex'
import { className } from './style'
import type { ToggleVariants } from './toggle'
import { tokens } from './tokens.stylex'
export type ToggleGroupItem<Value extends string = string>=Readonly<{value:Value;children:ReadonlyArray<Html|string>;isDisabled?:boolean;layoutStyle?:ComponentLayoutStyle}>
type SingleSelection<Value extends string>=Readonly<{value:Value;values?:never}>;type MultipleSelection<Value extends string>=Readonly<{value?:never;values:ReadonlyArray<Value>}>
export type ToggleGroupProps<Msg, Value extends string = string>=Readonly<{ariaLabel?:string;items:ReadonlyArray<ToggleGroupItem<Value>>;onToggle:(itemValue:Value)=>Msg;arrangement?:'joined'|'wrapped';variant?:ToggleVariants['variant'];size?:ToggleVariants['size'];layoutStyle?:ComponentLayoutStyle}>& (SingleSelection<Value>|MultipleSelection<Value>)
const styles=stylex.create({group:{borderRadius:foundationTokens.radiusMd, gap:0, alignItems:'center', display:'flex', width:'fit-content',},groupWrapped:{gap:'0.25rem',flexWrap:'wrap'},outlineGroup:{boxShadow:foundationTokens.shadowXs},item:{borderColor:foundationTokens.transparent, borderRadius:'0px', borderStyle:'solid', borderWidth:0, gap:'0.5rem', paddingInline:'0.75rem', alignItems:'center', backgroundColor:{default:foundationTokens.transparent,':hover':foundationTokens.muted}, color:tokens.foreground, display:'inline-flex', fontSize:'0.875rem', fontWeight:500, justifyContent:'center', height:'2.25rem', minWidth:0,},itemWrapped:{borderRadius:foundationTokens.radiusMd},outline:{borderColor:tokens.input,borderWidth:1},pressed:{backgroundColor:tokens.accent,color:tokens.accentForeground},disabled:{opacity:.5,pointerEvents:'none'},sm:{height:'2rem'},lg:{height:'2.5rem'}})
export const toggleGroup=<Msg, Value extends string = string>(p:ToggleGroupProps<Msg, Value>,h:HtmlBuilder<Msg>):Html=>{const variant=p.variant??'default',size=p.size??'default',wrapped=p.arrangement==='wrapped',selected:ReadonlyArray<Value>=p.values===undefined?[p.value]:p.values;return h.div([h.Role('group'),...(p.ariaLabel===undefined?[]:[h.AriaLabel(p.ariaLabel)]),h.DataAttribute('slot','toggle-group'),h.DataAttribute('variant',variant),h.DataAttribute('size',size),h.DataAttribute('spacing','0'),h.Class(className(styles.group,wrapped&&styles.groupWrapped,variant==='outline'&&styles.outlineGroup,p.layoutStyle))],p.items.map(item=>ButtonPrimitive.view({onClick:p.onToggle(item.value),isDisabled:item.isDisabled??false,type:'button',toView:({button})=>h.button([...button,h.DataAttribute('slot','toggle-group-item'),h.DataAttribute('variant',variant),h.DataAttribute('size',size),h.DataAttribute('spacing','0'),h.AriaPressed(selected.includes(item.value)?'true':'false'),h.Class(className(styles.item,wrapped&&styles.itemWrapped,variant==='outline'&&styles.outline,size==='sm'&&styles.sm,size==='lg'&&styles.lg,selected.includes(item.value)&&styles.pressed,item.isDisabled&&styles.disabled,item.layoutStyle))],[...item.children])},h)))}

