import * as stylex from '@stylexjs/stylex'

export const tokens = stylex.defineVars({
  background: 'var(--background)',
  foreground: 'var(--foreground)',
  card: 'var(--card)',
  cardForeground: 'var(--card-foreground)',
  primary: 'var(--primary)',
  primaryForeground: 'var(--primary-foreground)',
  secondary: 'var(--secondary)',
  secondaryForeground: 'var(--secondary-foreground)',
  mutedForeground: 'var(--muted-foreground)',
  accent: 'var(--accent)',
  accentForeground: 'var(--accent-foreground)',
  destructive: 'var(--destructive)',
  destructiveForeground: 'oklch(0.985 0 0)',
  destructiveHover: 'color-mix(in oklab, var(--destructive) 90%, transparent)',
  destructiveSurface: 'var(--stylex-destructive-surface)',
  inputSurface: 'var(--stylex-input-surface)',
  outlineSurface: 'var(--stylex-outline-surface)',
  outlineHover: 'var(--stylex-outline-hover)',
  primaryHover: 'color-mix(in oklab, var(--primary) 90%, transparent)',
  secondaryHover: 'color-mix(in oklab, var(--secondary) 80%, transparent)',
  border: 'var(--border)',
  input: 'var(--input)',
  ring: 'var(--ring)',
  radius: 'var(--radius)',
  controlRadius: 'calc(var(--radius) - 2px)',
  cardRadius: 'calc(var(--radius) + 4px)',
  focusRingShadow: '0 0 0 3px color-mix(in oklab, var(--ring) 50%, transparent)',
  destructiveRingShadow:
    '0 0 0 3px color-mix(in oklab, var(--destructive) 20%, transparent)',
  shadowSm: '0 1px 2px rgb(0 0 0 / 0.05)',
  shadowCard: '0 1px 3px rgb(0 0 0 / 0.1), 0 1px 2px rgb(0 0 0 / 0.06)',
  shadowNone: 'none',
  transparent: 'transparent',
  backdrop: 'rgb(0 0 0 / 0.5)',
})

