import { Option, Schema as S } from 'effect'; import { Command } from 'foldkit'; import * as FoldkitCalendar from 'foldkit/calendar'; import { defineMessageUnion } from 'foldkit/message';
import { definePreviewProgram } from '@/docs/components/pages/authored-page'; import * as DatePicker from '@/ui/date-picker';
    const Message = defineMessageUnion({
  'GotDatePickerPreviewMessage': { message: DatePicker.Message },
  'ChangedDatePickerQuery': { value: S.String },
  'LoadedExternalDate': {},
  'ClearedDatePickerSelection': {},
}); type Message = typeof Message.Type;
const Model = S.Struct({ _docsPage: S.Literal('date-picker'), datePicker: DatePicker.Model, selectedDate: S.Option(FoldkitCalendar.CalendarDate), query: S.String, parseError: S.NullOr(S.String) }); type Model = typeof Model.Type;
const encodeDate = S.encodeSync(FoldkitCalendar.CalendarDateFromIsoString); const parseDate = (value: string): Option.Option<FoldkitCalendar.CalendarDate> => { try { return Option.some(S.decodeUnknownSync(FoldkitCalendar.CalendarDateFromIsoString)(value)); } catch { return Option.none(); } };
export const datePickerTailwindPreviewProgram = definePreviewProgram<Model, Message>({ Model, Message, init: index => { const initialDate = { year: 2026, month: 7, day: 18 }; const selectedDate = index === 0 ? Option.some(initialDate) : Option.none<FoldkitCalendar.CalendarDate>(); return { _docsPage: 'date-picker', datePicker: DatePicker.init({ id: `docs-date-picker-${String(index)}`, today: FoldkitCalendar.fromDateInZone(new Date('2026-07-28T12:00:00Z'), 'Europe/Berlin'), initialViewDate: initialDate, isAnimated: true }), selectedDate, query: Option.match(selectedDate, { onNone: () => '', onSome: encodeDate }), parseError: null }; }, update: (model, message) => { if (message._tag === 'ChangedDatePickerQuery') { const maybeDate = parseDate(message.value); return { model: Option.match(maybeDate, { onNone: () => ({ ...model, query: message.value, parseError: message.value === '' ? null : 'Enter a real date as YYYY-MM-DD.' }), onSome: date => ({ ...model, datePicker: DatePicker.focusDate(model.datePicker, date), selectedDate: Option.some(date), query: message.value, parseError: null }) }) }; } if (message._tag === 'LoadedExternalDate') { const date = { year: 2026, month: 8, day: 12 }; return { model: { ...model, datePicker: DatePicker.focusDate(model.datePicker, date), selectedDate: Option.some(date), query: encodeDate(date), parseError: null } }; } const { model: datePicker, commands: datePickerCommands__, outMessage: datePickerOut__ } = message._tag === 'ClearedDatePickerSelection' ? DatePicker.clear(model.datePicker) : DatePicker.update(model.datePicker, message.message);
const commands = datePickerCommands__ ?? [];
const output = Option.fromNullishOr(datePickerOut__); const selectedDate = Option.match(output, { onNone: () => model.selectedDate, onSome: value => value._tag === 'SelectedDate' ? Option.some(value.date) : value._tag === 'ClearedDate' ? Option.none() : model.selectedDate }); const query = Option.match(output, { onNone: () => model.query, onSome: value => value._tag === 'SelectedDate' ? encodeDate(value.date) : value._tag === 'ClearedDate' ? '' : model.query }); return { model: { ...model, datePicker, selectedDate, query, parseError: null }, commands: Command.mapMessages(commands, next => Message['GotDatePickerPreviewMessage']({ message: next })) }; }, view: (index, model, h) => h.form([h.OnSubmit(Message['LoadedExternalDate']({}))], [DatePicker.datePicker({ model: model.datePicker, maybeSelectedDate: model.selectedDate, query: model.query, onQueryInput: value => Message['ChangedDatePickerQuery']({ value }), inputLabel: 'Due date (YYYY-MM-DD)', ...(model.parseError === null ? {} : { parseError: model.parseError }), toParentMessage: message => Message['GotDatePickerPreviewMessage']({ message }), name: index === 0 ? 'dueDate' : 'newDueDate', ariaLabel: index === 0 ? 'Change due date' : 'Choose a new due date', placeholder: 'Pick a due date', mobilePresentation: 'dialog' }, h), h.div([h.Class('mt-3 flex items-center gap-2')], [h.button([h.Type('button'), h.OnClick(Message['LoadedExternalDate']({})), h.Class('rounded-md border px-3 py-2 text-sm')], ['Load saved date']), h.button([h.Type('button'), h.OnClick(Message['ClearedDatePickerSelection']({})), h.Disabled(Option.isNone(model.selectedDate) && model.query === ''), h.Class('rounded-md border px-3 py-2 text-sm disabled:opacity-50')], ['Clear date'])])]) });
