import * as stylex from '@stylexjs/stylex'
import { reset } from '@/stylex/reset'
import { className } from '@/stylex/style'

const styles = stylex.create({
  section: {
    marginInline: 'auto',
    width: '100%',
    maxWidth: '1200px',
    paddingInline: {
      default: '1rem',
      '@media (min-width: 768px)': '2rem',
    },
    paddingBlock: {
      default: '3.5rem',
      '@media (min-width: 768px)': '5rem',
    },
  },
  control: {
    height: '2.5rem',
    borderRadius: '9999px',
    paddingInline: '1rem',
    fontSize: '.875rem',
    lineHeight: '1.25rem',
    transitionProperty: 'background-color,color,box-shadow,scale',
    transitionDuration: '200ms',
    scale: {
      default: null,
      ':active': '.96',
    },
    outlineStyle: {
      default: null,
      ':focus-visible': 'none',
    },
    boxShadow: {
      default: null,
      ':focus-visible': '0 0 0 2px var(--ring)',
    },
  },
  subtleLink: {
    display: 'inline-flex',
    minHeight: '2.5rem',
    alignItems: 'center',
    gap: '0.5rem',
    fontSize: '.875rem',
    lineHeight: '1.25rem',
    fontWeight: 500,
    color: {
      default: 'var(--muted-foreground)',
      ':hover': 'var(--foreground)',
    },
    transitionProperty: 'color, background-color, border-color',
    transitionDuration: '.15s',
    borderRadius: {
      default: null,
      ':focus-visible': 'calc(var(--radius) - 2px)',
    },
    outlineStyle: {
      default: null,
      ':focus-visible': 'none',
    },
    boxShadow: {
      default: null,
      ':focus-visible': '0 0 0 2px var(--ring)',
    },
  },
  icon: {
    width: '1rem',
    height: '1rem',
  },
  checkIcon: {
    width: '0.875rem',
    height: '0.875rem',
  },
  sectionHeader: {
    marginBottom: {
      default: '2rem',
      '@media (min-width: 768px)': '2.5rem',
    },
    display: 'flex',
    maxWidth: '42rem',
    flexDirection: 'column',
    gap: '0.75rem',
  },
  sectionTitle: {
    fontSize: {
      default: '1.875rem',
      '@media (min-width: 640px)': '2.25rem',
    },
    lineHeight: 1.25,
    fontWeight: 600,
    letterSpacing: '-.025em',
    textWrap: 'balance',
  },
  sectionCopy: {
    maxWidth: '36rem',
    lineHeight: 1.625,
    textWrap: 'pretty',
    color: 'var(--muted-foreground)',
  },
  colorPicker: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.25rem',
  },
  colorButton: {
    display: 'flex',
    width: '2.5rem',
    height: '2.5rem',
    flexShrink: 0,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '9999px',
    outlineStyle: 'none',
    transitionProperty: 'box-shadow,scale',
    transitionDuration: '.15s',
    scale: {
      default: null,
      ':active': '.96',
    },
    boxShadow: {
      default: null,
      ':focus-visible': '0 0 0 2px var(--ring)',
    },
  },
  colorSelected: {
    display: 'flex',
    width: '1.5rem',
    height: '1.5rem',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '9999px',
    color: '#fff',
    boxShadow:
      '0 0 0 2px var(--background), 0 0 0 4px color-mix(in oklab, var(--foreground) 20%, transparent)',
  },
  colorIdle: {
    display: 'flex',
    width: '1.5rem',
    height: '1.5rem',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '9999px',
    color: '#fff',
    transitionProperty: 'transform, scale',
    transitionDuration: '.15s',
    scale: {
      default: null,
      ':hover': '1.1',
    },
  },
  showcaseFrame: {
    overflow: 'hidden',
    borderRadius: '1.5rem',
    backgroundColor: 'color-mix(in oklab, var(--muted) 50%, transparent)',
    padding: {
      default: '0.5rem',
      '@media (min-width: 640px)': '0.75rem',
    },
    boxShadow: '0 0 0 1px var(--border),0 12px 40px -24px rgba(0,0,0,0.18)',
  },
  frameToolbar: {
    display: 'flex',
    height: '2.5rem',
    alignItems: 'center',
    gap: '0.75rem',
    paddingInline: {
      default: '0.5rem',
      '@media (min-width: 640px)': '0.75rem',
    },
    paddingBottom: '0.5rem',
  },
  frameDots: {
    display: 'flex',
    flexShrink: 0,
    gap: '0.375rem',
  },
  frameDot: {
    width: '0.625rem',
    height: '0.625rem',
    borderRadius: '9999px',
    backgroundColor: 'color-mix(in oklab, var(--foreground) 20%, transparent)',
  },
  frameTitle: {
    fontSize: '.75rem',
    lineHeight: '1rem',
    fontWeight: 500,
    color: 'color-mix(in oklab, var(--foreground) 80%, transparent)',
  },
  frameStatus: {
    marginLeft: 'auto',
    display: 'inline-flex',
    flexShrink: 0,
    alignItems: 'center',
    gap: '0.375rem',
    fontSize: '.75rem',
    lineHeight: '1rem',
    color: 'var(--muted-foreground)',
  },
  statusDot: {
    width: '0.375rem',
    height: '0.375rem',
    borderRadius: '9999px',
    backgroundColor: 'oklch(.696 .17 162.48)',
  },
  frameContent: {
    overflow: 'hidden',
    borderRadius: 'calc(var(--radius) + 4px)',
    backgroundColor: 'var(--background)',
    boxShadow: '0 0 0 1px var(--border)',
  },
  iframe: {
    display: 'block',
    height: {
      default: '620px',
      '@media (min-width: 640px)': '680px',
    },
    width: '100%',
    borderWidth: 0,
    backgroundColor: 'var(--background)',
  },
  showcaseBody: {
    position: 'relative',
    display: 'flex',
    minWidth: 0,
    flexDirection: 'column',
    gap: '1rem',
  },
  showcasePicker: {
    alignSelf: 'flex-start',
    position: {
      default: null,
      '@media (min-width: 768px)': 'absolute',
    },
    top: {
      default: null,
      '@media (min-width: 768px)': '-0.125rem',
    },
    right: {
      default: null,
      '@media (min-width: 768px)': '0rem',
    },
    zIndex: {
      default: null,
      '@media (min-width: 768px)': 10,
    },
  },
  showcaseFooter: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 'NaNrem',
  },
  mutedSmall: {
    fontSize: '.875rem',
    lineHeight: '1.25rem',
    color: 'var(--muted-foreground)',
  },
  showcaseLinks: {
    display: 'flex',
    alignItems: 'center',
    gap: '1.25rem',
  },
  choices: {
    display: 'grid',
    gap: '0.75rem',
  },
  label: {
    fontSize: '.875rem',
    lineHeight: '1.25rem',
    fontWeight: 500,
  },
  choiceRow: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '0.5rem',
  },
  choiceSelected: {
    height: '2.5rem',
    borderRadius: '9999px',
    paddingInline: '1rem',
    fontSize: '.875rem',
    lineHeight: '1.25rem',
    transitionProperty: 'background-color,color,box-shadow,scale',
    transitionDuration: '200ms',
    backgroundColor: 'var(--foreground)',
    color: 'var(--background)',
    scale: {
      default: null,
      ':active': '.96',
    },
    outlineStyle: {
      default: null,
      ':focus-visible': 'none',
    },
    boxShadow: {
      default: null,
      ':focus-visible': '0 0 0 2px var(--ring)',
    },
  },
  choiceIdle: {
    height: '2.5rem',
    borderRadius: '9999px',
    paddingInline: '1rem',
    fontSize: '.875rem',
    lineHeight: '1.25rem',
    transitionProperty: 'background-color,color,box-shadow,scale',
    transitionDuration: '200ms',
    backgroundColor: {
      default: 'color-mix(in oklab, var(--muted) 70%, transparent)',
      ':hover': 'var(--muted)',
    },
    color: {
      default: 'color-mix(in oklab, var(--foreground) 75%, transparent)',
      ':hover': 'var(--foreground)',
    },
    scale: {
      default: null,
      ':active': '.96',
    },
    outlineStyle: {
      default: null,
      ':focus-visible': 'none',
    },
    boxShadow: {
      default: null,
      ':focus-visible': '0 0 0 2px var(--ring)',
    },
  },
  initials: {
    display: 'flex',
    width: '2.25rem',
    height: '2.25rem',
    flexShrink: 0,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '9999px',
    backgroundColor: 'color-mix(in oklab, var(--primary) 10%, transparent)',
    fontSize: '.75rem',
    lineHeight: '1rem',
    fontWeight: 500,
    color: 'var(--foreground)',
  },
  studioLayout: {
    display: 'grid',
    gap: {
      default: '2.5rem',
      '@media (min-width: 1024px)': '3.5rem',
    },
    gridTemplateColumns: {
      default: null,
      '@media (min-width: 1024px)': '280px minmax(0,1fr)',
    },
  },
  studioControls: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1.75rem',
  },
  gridTight: {
    display: 'grid',
    gap: '0.5rem',
  },
  studioRoot: {
    minWidth: 0,
  },
  studioPreview: {
    display: 'grid',
    minHeight: '420px',
    placeItems: 'center',
    borderRadius: '1rem',
    backgroundColor: 'color-mix(in oklab, var(--muted) 40%, transparent)',
    padding: {
      default: '1.25rem',
      '@media (min-width: 640px)': '2.5rem',
    },
  },
  studioCard: {
    width: '100%',
    maxWidth: '28rem',
    overflow: 'hidden',
    borderRadius: 'calc(var(--radius) + 8px)',
    backgroundColor: 'var(--card)',
    color: 'var(--card-foreground)',
    boxShadow: '0 0 0 1px var(--border),0 16px 40px -20px rgba(0,0,0,0.15)',
  },
  studioHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.75rem',
    borderBottom: '1px solid var(--border)',
    padding: '1.5rem',
  },
  studioLogo: {
    display: 'flex',
    width: '2.5rem',
    height: '2.5rem',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 'var(--radius)',
    backgroundColor: 'var(--primary)',
    color: 'var(--primary-foreground)',
  },
  cardTitle: {
    fontSize: '1rem',
    lineHeight: '1.5rem',
    fontWeight: 600,
  },
  caption: {
    marginTop: '0.25rem',
    fontSize: '.75rem',
    lineHeight: '1rem',
    color: 'var(--muted-foreground)',
  },
  pushRight: {
    marginLeft: 'auto',
  },
  studioBody: {
    display: 'grid',
    gap: '1.25rem',
    padding: '1.5rem',
  },
  row: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.75rem',
  },
  mutedCaption: {
    fontSize: '.75rem',
    lineHeight: '1rem',
    color: 'var(--muted-foreground)',
  },
  memberRole: {
    marginLeft: 'auto',
    fontSize: '.75rem',
    lineHeight: '1rem',
    color: 'var(--muted-foreground)',
  },
  studioNotifications: {
    borderTop: '1px solid var(--border)',
    paddingTop: '1.25rem',
  },
  studioPreset: {
    marginTop: '0.75rem',
    textAlign: 'center',
    fontFamily:
      'var(--font-mono, ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace)',
    fontSize: '11px',
    color: 'var(--muted-foreground)',
  },
  inspectorLine: {
    display: 'flex',
    minWidth: 0,
    gap: '0.5rem',
  },
  inspectorKey: {
    flexShrink: 0,
    color: 'oklch(.705 .015 286.067)',
  },
  inspectorString: {
    wordBreak: 'break-all',
    color: 'oklch(.924 .12 95.746)',
  },
  inspectorValue: {
    color: 'oklch(.845 .143 164.978)',
  },
  inspectorPunctuation: {
    color: 'oklch(.705 .015 286.067)',
  },
  stateLayout: {
    display: 'grid',
    overflow: 'hidden',
    borderRadius: '1rem',
    backgroundColor: 'color-mix(in oklab, var(--muted) 30%, transparent)',
    boxShadow: '0 0 0 1px var(--border)',
    gridTemplateColumns: {
      default: null,
      '@media (min-width: 768px)': 'repeat(2,minmax(0,1fr))',
    },
  },
  stateControls: {
    display: 'flex',
    minWidth: 0,
    flexDirection: 'column',
    justifyContent: 'center',
    gap: '1.5rem',
    padding: {
      default: '1.5rem',
      '@media (min-width: 640px)': '2.5rem',
    },
  },
  between: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  stateFooter: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '1rem',
    borderTop: '1px solid var(--border)',
    paddingTop: '1.25rem',
  },
  inspector: {
    display: 'flex',
    minWidth: 0,
    flexDirection: 'column',
    backgroundColor: 'oklch(.141 .005 285.823)',
    color: 'oklch(.967 .001 286.375)',
  },
  inspectorHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottom: '1px solid var(--border)',
    borderColor: 'rgb(255 255 255 / 10%)',
    paddingInline: '1.5rem',
    paddingBlock: '1rem',
  },
  inspectorLabel: {
    fontFamily:
      'var(--font-mono, ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace)',
    fontSize: '.75rem',
    lineHeight: '1rem',
    color: 'oklch(.705 .015 286.067)',
  },
  liveLabel: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '0.375rem',
    fontSize: '11px',
    color: 'oklch(.845 .143 164.978)',
  },
  liveDot: {
    width: '0.375rem',
    height: '0.375rem',
    borderRadius: '9999px',
    backgroundColor: 'oklch(.765 .177 163.223)',
  },
  inspectorBody: {
    minHeight: '11rem',
    paddingInline: '1.5rem',
    paddingBlock: '1.5rem',
    fontFamily:
      'var(--font-mono, ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace)',
    fontSize: {
      default: '.75rem',
      '@media (min-width: 640px)': '.875rem',
    },
    lineHeight: '1.75rem',
  },
  eventLog: {
    marginTop: 'auto',
    borderTop: '1px solid var(--border)',
    borderColor: 'rgb(255 255 255 / 10%)',
    paddingInline: '1.5rem',
    paddingBlock: '1.25rem',
  },
  eventLogLabel: {
    marginBottom: '0.75rem',
    fontSize: '10px',
    letterSpacing: '.1em',
    color: 'oklch(.705 .015 286.067)',
    textTransform: 'uppercase',
  },
  eventRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.75rem',
    fontFamily:
      'var(--font-mono, ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace)',
    fontSize: '11px',
  },
  eventActiveDot: {
    width: '0.25rem',
    height: '0.25rem',
    borderRadius: '9999px',
    backgroundColor: 'oklch(.765 .177 163.223)',
  },
  eventIdleDot: {
    width: '0.25rem',
    height: '0.25rem',
    borderRadius: '9999px',
    backgroundColor: 'oklch(.442 .017 285.786)',
  },
  eventActive: {
    color: 'oklch(.92 .004 286.32)',
  },
  dialogCode: {
    borderRadius: 'var(--radius)',
    backgroundColor: 'var(--muted)',
    padding: '1rem',
    fontFamily:
      'var(--font-mono, ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace)',
    fontSize: '.75rem',
    lineHeight: '1rem',
  },
  dialogClose: {
    height: '2.5rem',
    borderRadius: 'calc(var(--radius) - 2px)',
    backgroundColor: 'var(--primary)',
    paddingInline: '1rem',
    fontSize: '.875rem',
    lineHeight: '1.25rem',
    fontWeight: 500,
    color: 'var(--primary-foreground)',
  },
  demoCard: {
    display: 'flex',
    minWidth: 0,
    flexDirection: 'column',
    borderRadius: '1rem',
    backgroundColor: 'var(--background)',
    boxShadow: '0 0 0 1px var(--border)',
  },
  demoContent: {
    display: 'flex',
    minHeight: '13rem',
    flex: '1 1 0%',
    flexDirection: 'column',
    justifyContent: 'center',
    gap: '1rem',
    padding: '1.5rem',
  },
  demoFooter: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: '0.75rem',
    borderTop: '1px solid var(--border)',
    paddingInline: '1.5rem',
    paddingBlock: '1.25rem',
  },
  demoTitle: {
    fontSize: '.875rem',
    lineHeight: '1.25rem',
    fontWeight: 600,
  },
  demoDescription: {
    marginTop: '0.25rem',
    fontSize: '.75rem',
    lineHeight: 1.625,
    color: 'var(--muted-foreground)',
  },
  demoLink: {
    display: 'flex',
    width: '2.5rem',
    height: '2.5rem',
    flexShrink: 0,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '9999px',
    color: {
      default: 'var(--muted-foreground)',
      ':hover': 'var(--foreground)',
    },
    transitionProperty: 'color, background-color, border-color',
    transitionDuration: '.15s',
    backgroundColor: {
      default: null,
      ':hover': 'var(--muted)',
    },
    outlineStyle: {
      default: null,
      ':focus-visible': 'none',
    },
    boxShadow: {
      default: null,
      ':focus-visible': '0 0 0 2px var(--ring)',
    },
  },
  srOnly: {
    position: 'absolute',
    width: '1px',
    height: '1px',
    padding: 0,
    margin: '-1px',
    overflow: 'hidden',
    clip: 'rect(0,0,0,0)',
    whiteSpace: 'nowrap',
    borderWidth: 0,
  },
  tableSort: {
    textAlign: 'right',
  },
  playgroundHeader: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    gap: '1.25rem',
  },
  playgroundLink: {
    display: 'inline-flex',
    minHeight: '2.5rem',
    alignItems: 'center',
    gap: '0.5rem',
    fontSize: '.875rem',
    lineHeight: '1.25rem',
    fontWeight: 500,
    color: {
      default: 'var(--muted-foreground)',
      ':hover': 'var(--foreground)',
    },
    transitionProperty: 'color, background-color, border-color',
    transitionDuration: '.15s',
    marginBottom: '2.5rem',
    borderRadius: {
      default: null,
      ':focus-visible': 'calc(var(--radius) - 2px)',
    },
    outlineStyle: {
      default: null,
      ':focus-visible': 'none',
    },
    boxShadow: {
      default: null,
      ':focus-visible': '0 0 0 2px var(--ring)',
    },
  },
  playgroundGrid: {
    display: 'grid',
    gap: '1.25rem',
    gridTemplateColumns: {
      default: null,
      '@media (min-width: 640px)': 'repeat(2,minmax(0,1fr))',
      '@media (min-width: 1024px)': 'repeat(3,minmax(0,1fr))',
    },
  },
  center: {
    display: 'flex',
    justifyContent: 'center',
  },
  centeredCaption: {
    textAlign: 'center',
    fontSize: '.75rem',
    lineHeight: '1rem',
    color: 'var(--muted-foreground)',
  },
  formError: {
    fontSize: '.75rem',
    lineHeight: '1rem',
    color: 'var(--destructive)',
  },
  formSuccess: {
    fontSize: '.75rem',
    lineHeight: '1rem',
    color: {
      default: 'oklch(.508 .118 165.612)',
      ':is(.dark *)': 'oklch(.765 .177 163.223)',
    },
  },
  chartCard: {
    borderRadius: '1rem',
    backgroundColor: 'var(--background)',
    padding: {
      default: '1.25rem',
      '@media (min-width: 640px)': '2rem',
    },
    boxShadow: '0 0 0 1px var(--border)',
  },
  chartHeader: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: '1.25rem',
  },
  chartTotal: {
    marginTop: '0.5rem',
    fontSize: '1.875rem',
    lineHeight: '2.25rem',
    fontWeight: 600,
    letterSpacing: '-.025em',
    fontVariantNumeric: 'tabular-nums',
  },
  chartPeriods: {
    display: 'flex',
    borderRadius: '9999px',
    backgroundColor: 'color-mix(in oklab, var(--muted) 70%, transparent)',
    padding: '0.25rem',
  },
  periodSelected: {
    height: '2.5rem',
    borderRadius: '9999px',
    paddingInline: '1rem',
    fontSize: '.875rem',
    lineHeight: '1.25rem',
    transitionProperty: 'background-color,color,box-shadow,scale',
    transitionDuration: '200ms',
    backgroundColor: 'var(--background)',
    color: 'var(--foreground)',
    boxShadow: {
      default: '0 1px 3px rgb(0 0 0 / .1), 0 1px 2px -1px rgb(0 0 0 / .1)',
      ':focus-visible': '0 0 0 2px var(--ring)',
    },
    scale: {
      default: null,
      ':active': '.96',
    },
    outlineStyle: {
      default: null,
      ':focus-visible': 'none',
    },
  },
  periodIdle: {
    height: '2.5rem',
    borderRadius: '9999px',
    paddingInline: '1rem',
    fontSize: '.875rem',
    lineHeight: '1.25rem',
    transitionProperty: 'background-color,color,box-shadow,scale',
    transitionDuration: '200ms',
    color: {
      default: 'color-mix(in oklab, var(--foreground) 75%, transparent)',
      ':hover': 'var(--foreground)',
    },
    scale: {
      default: null,
      ':active': '.96',
    },
    outlineStyle: {
      default: null,
      ':focus-visible': 'none',
    },
    boxShadow: {
      default: null,
      ':focus-visible': '0 0 0 2px var(--ring)',
    },
  },
  chartSeries: {
    marginTop: '2rem',
    display: 'flex',
    flexWrap: 'wrap',
    gap: '0.5rem',
  },
  seriesSelected: {
    height: '2.5rem',
    borderRadius: '9999px',
    paddingInline: '1rem',
    fontSize: '.875rem',
    lineHeight: '1.25rem',
    transitionProperty: 'background-color,color,box-shadow,scale',
    transitionDuration: '200ms',
    backgroundColor: 'var(--muted)',
    color: 'var(--foreground)',
    scale: {
      default: null,
      ':active': '.96',
    },
    outlineStyle: {
      default: null,
      ':focus-visible': 'none',
    },
    boxShadow: {
      default: null,
      ':focus-visible': '0 0 0 2px var(--ring)',
    },
  },
  seriesIdle: {
    height: '2.5rem',
    borderRadius: '9999px',
    paddingInline: '1rem',
    fontSize: '.875rem',
    lineHeight: '1.25rem',
    transitionProperty: 'background-color,color,box-shadow,scale',
    transitionDuration: '200ms',
    color: 'color-mix(in oklab, var(--foreground) 75%, transparent)',
    scale: {
      default: null,
      ':active': '.96',
    },
    outlineStyle: {
      default: null,
      ':focus-visible': 'none',
    },
    boxShadow: {
      default: null,
      ':focus-visible': '0 0 0 2px var(--ring)',
    },
    backgroundColor: {
      default: 'transparent',
      ':hover': 'color-mix(in oklab, var(--muted) 50%, transparent)',
    },
  },
  chartFooter: {
    marginTop: '0.75rem',
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '0.75rem',
    borderTop: '1px solid var(--border)',
    paddingTop: '1.25rem',
  },
  chartLegend: {
    display: 'flex',
    alignItems: 'center',
    gap: '1.25rem',
    fontSize: '.75rem',
    lineHeight: '1rem',
    color: 'var(--muted-foreground)',
  },
  legendItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
  },
  visitorsDot: {
    width: '0.5rem',
    height: '0.5rem',
    borderRadius: '9999px',
    backgroundColor: 'var(--chart-1)',
  },
  signupsDot: {
    width: '0.5rem',
    height: '0.5rem',
    borderRadius: '9999px',
    backgroundColor: 'var(--chart-2)',
  },
  gettingStarted: {
    display: 'grid',
    alignItems: 'center',
    gap: '2rem',
    borderRadius: '1rem',
    backgroundColor: 'color-mix(in oklab, var(--muted) 40%, transparent)',
    padding: {
      default: '1.5rem',
      '@media (min-width: 640px)': '2.5rem',
    },
    gridTemplateColumns: {
      default: null,
      '@media (min-width: 1024px)': '1fr 1.2fr',
    },
  },
  grid: {
    display: 'grid',
    gap: '1rem',
  },
  gettingStartedTitle: {
    fontSize: {
      default: '1.5rem',
      '@media (min-width: 640px)': '1.875rem',
    },
    lineHeight: {
      default: '2rem',
      '@media (min-width: 640px)': '2.25rem',
    },
    fontWeight: 600,
    letterSpacing: '-.025em',
    textWrap: 'balance',
  },
  gettingStartedCopy: {
    maxWidth: '24rem',
    fontSize: '.875rem',
    lineHeight: 1.625,
    textWrap: 'pretty',
    color: 'var(--muted-foreground)',
  },
  actions: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '0.75rem',
  },
  terminal: {
    minWidth: 0,
    borderRadius: 'calc(var(--radius) + 4px)',
    backgroundColor: 'var(--background)',
    padding: '1.25rem',
    boxShadow: '0 0 0 1px var(--border)',
  },
  terminalHeader: {
    marginBottom: '1rem',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  terminalLabel: {
    fontFamily:
      'var(--font-mono, ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace)',
    fontSize: '.75rem',
    lineHeight: '1rem',
    color: 'var(--muted-foreground)',
  },
  terminalRow: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: '0.75rem',
  },
  terminalPrompt: {
    fontFamily:
      'var(--font-mono, ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace)',
    fontSize: '.875rem',
    lineHeight: '1.25rem',
    color: 'var(--muted-foreground)',
  },
  terminalCode: {
    minWidth: 0,
    flex: '1 1 0%',
    fontFamily:
      'var(--font-mono, ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace)',
    fontSize: {
      default: '.75rem',
      '@media (min-width: 640px)': '.875rem',
    },
    lineHeight: '1.5rem',
    overflowWrap: 'break-word',
  },
  terminalFooter: {
    marginTop: '1rem',
    borderTop: '1px solid var(--border)',
    paddingTop: '1rem',
    fontSize: '.75rem',
    lineHeight: 1.625,
    color: 'var(--muted-foreground)',
  },
  faq: {
    marginInline: 'auto',
    display: 'grid',
    width: '100%',
    maxWidth: '1200px',
    gap: '2rem',
    paddingInline: {
      default: '1rem',
      '@media (min-width: 768px)': '2rem',
    },
    paddingBlock: {
      default: '3.5rem',
      '@media (min-width: 768px)': '5rem',
    },
    gridTemplateColumns: {
      default: null,
      '@media (min-width: 768px)': '1fr 1.5fr',
    },
  },
  faqIntro: {
    maxWidth: '24rem',
  },
  faqTitle: {
    fontSize: {
      default: '1.5rem',
      '@media (min-width: 640px)': '1.875rem',
    },
    lineHeight: {
      default: '2rem',
      '@media (min-width: 640px)': '2.25rem',
    },
    fontWeight: 600,
    letterSpacing: '-.025em',
  },
  faqCopy: {
    marginTop: '0.75rem',
    fontSize: '.875rem',
    lineHeight: 1.625,
    color: 'var(--muted-foreground)',
  },
  faqItem: {
    borderBottom: '1px solid var(--border)',
    paddingBlock: '1.25rem',
    paddingTop: {
      default: null,
      ':first-child': '0rem',
    },
  },
  faqSummary: {
    display: 'flex',
    minHeight: '2.5rem',
    cursor: 'pointer',
    listStyleType: 'none',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '1rem',
    borderRadius: 'calc(var(--radius) - 4px)',
    fontSize: '.875rem',
    lineHeight: '1.25rem',
    fontWeight: 500,
    outlineStyle: 'none',
    boxShadow: {
      default: null,
      ':focus-visible': '0 0 0 2px var(--ring)',
    },
    '::-webkit-details-marker': {
      display: 'none',
    },
  },
  faqIcon: {
    fontSize: '1.125rem',
    lineHeight: '1.75rem',
    fontWeight: 400,
    color: 'var(--muted-foreground)',
    transitionProperty: 'transform, scale',
    transitionDuration: '.15s',
    transform: {
      default: null,
      ':is(details[open] *)': 'rotate(45deg)',
    },
  },
  faqAnswer: {
    maxWidth: '32rem',
    paddingTop: '0.75rem',
    fontSize: '.875rem',
    lineHeight: 1.625,
    textWrap: 'pretty',
    color: 'var(--muted-foreground)',
  },
  deprecatedInk: {
    color: {
      default: 'oklch(.505 .213 27.518)',
      ':is(.dark *)': 'oklch(.704 .191 22.216)',
    },
  },
})

// Element defaults stay local to the landing composition.
export const tourSkin = Object.fromEntries(
  Object.entries(styles).map(([key, style]) => [
    key,
    [
      className(reset.button, reset.text, reset.link, reset.list, style),
      key === 'studioRoot'
        ? 'landing-studio'
        : key === 'studioPreview'
          ? 'create-board-theme'
          : '',
    ]
      .filter(Boolean)
      .join(' '),
  ]),
) as Record<keyof typeof styles, string>
