import * as stylex from '@stylexjs/stylex'
import { reset } from '@/stylex/reset'
import { className } from '@/stylex/style'

const styles = stylex.create({
  sectionHeading: {
    display: 'flex',
    maxWidth: '42rem',
    flexDirection: 'column',
    gap: '.75rem',
  },
  sectionTitle: {
    fontSize: { default: '1.5rem', '@media (min-width: 640px)': '1.875rem' },
    lineHeight: { default: '2rem', '@media (min-width: 640px)': '2.25rem' },
    fontWeight: 600,
    letterSpacing: '-.025em',
    textWrap: 'balance',
  },
  sectionCopy: { color: 'var(--muted-foreground)', textWrap: 'balance' },
  collage: { display: 'grid', width: '100%', maxWidth: '36rem', gap: '1rem' },
  collageRow: {
    display: 'grid',
    gridTemplateColumns: 'minmax(0,1fr) auto',
    alignItems: 'start',
    gap: '1rem',
  },
  badges: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: '.5rem',
  },
  keyHints: {
    color: 'var(--muted-foreground)',
    marginTop: '.5rem',
    display: 'flex',
    alignItems: 'center',
    gap: '.25rem',
    fontSize: '.75rem',
    lineHeight: '1rem',
  },
  hero: {
    marginInline: 'auto',
    display: 'grid',
    width: '100%',
    maxWidth: '1200px',
    alignItems: 'center',
    gap: '3rem',
    paddingInline: { default: '1rem', '@media (min-width: 768px)': '2rem' },
    paddingBlock: { default: '4rem', '@media (min-width: 768px)': '6rem' },
    gridTemplateColumns: {
      default: 'minmax(0,1fr)',
      '@media (min-width: 768px)': 'repeat(2,minmax(0,1fr))',
    },
  },
  heroCopy: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: '1.5rem',
  },
  brandRow: { display: 'flex', alignItems: 'center', gap: '.75rem' },
  logo: {
    width: '2.5rem',
    height: '2.5rem',
    borderRadius: '9px',
    display: 'block',
  },
  brand: {
    fontSize: '1.125rem',
    lineHeight: '1.75rem',
    fontWeight: 600,
    letterSpacing: '-.025em',
  },
  accent: { color: 'oklch(.62 .15 145)' },
  heroTitle: {
    fontSize: { default: '2.25rem', '@media (min-width: 640px)': '3rem' },
    // TW's leading-[1.1] emits a unitless line-height that scales with the
    // responsive font size (39.6px at text-4xl, 52.8px at sm:text-5xl).
    lineHeight: 1.1,
    fontWeight: 600,
    letterSpacing: '-.025em',
    textWrap: 'balance',
  },
  heroDescription: {
    color: 'var(--muted-foreground)',
    maxWidth: '28rem',
    fontSize: '1.125rem',
    lineHeight: '1.75rem',
    textWrap: 'balance',
  },
  actions: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: '.75rem',
  },
  license: {
    color: 'var(--muted-foreground)',
    fontSize: '.75rem',
    lineHeight: '1rem',
  },
  section: {
    marginInline: 'auto',
    display: 'flex',
    width: '100%',
    maxWidth: '1200px',
    flexDirection: 'column',
    gap: '2rem',
    paddingInline: { default: '1rem', '@media (min-width: 768px)': '2rem' },
    paddingBlock: '4rem',
  },
  comparison: {
    position: 'relative',
    width: '100%',
    cursor: 'ew-resize',
    touchAction: 'none',
    overflow: 'hidden',
    borderRadius: '.75rem',
    borderStyle: 'solid',
    borderWidth: 1,
    borderColor: 'var(--border)',
    userSelect: 'none',
  },
  image: { display: 'block', width: '100%', height: 'auto' },
  overlay: { position: 'absolute', inset: 0 },
  divider: {
    backgroundColor: 'color-mix(in oklab,var(--foreground) 60%,transparent)',
    pointerEvents: 'none',
    position: 'absolute',
    insetBlock: 0,
    width: '1px',
  },
  leftLabel: {
    backgroundColor: 'color-mix(in oklab,var(--background) 90%,transparent)',
    color: 'var(--foreground)',
    pointerEvents: 'none',
    position: 'absolute',
    top: '.75rem',
    left: '.75rem',
    borderRadius: '.375rem',
    borderStyle: 'solid',
    borderWidth: 1,
    borderColor: 'var(--border)',
    padding: '.25rem .5rem',
    fontSize: '.75rem',
    lineHeight: '1rem',
    fontWeight: 500,
  },
  rightLabel: {
    backgroundColor: 'color-mix(in oklab,var(--background) 90%,transparent)',
    color: 'var(--foreground)',
    pointerEvents: 'none',
    position: 'absolute',
    top: '.75rem',
    right: '.75rem',
    borderRadius: '.375rem',
    borderStyle: 'solid',
    borderWidth: 1,
    borderColor: 'var(--border)',
    padding: '.25rem .5rem',
    fontSize: '.75rem',
    lineHeight: '1rem',
    fontWeight: 500,
  },
  range: {
    position: 'absolute',
    inset: 0,
    height: '100%',
    width: '100%',
    cursor: 'ew-resize',
    opacity: 0,
  },
  layer: {
    display: 'flex',
    flexDirection: 'column',
    gap: '.25rem',
    borderRadius: '.75rem',
    borderStyle: 'solid',
    borderWidth: 1,
    borderColor: 'var(--border)',
    padding: '1rem',
  },
  label: { fontSize: '.875rem', lineHeight: '1.25rem', fontWeight: 600 },
  muted: {
    color: 'var(--muted-foreground)',
    fontSize: '.875rem',
    lineHeight: '1.25rem',
  },
  band: {
    backgroundColor: 'color-mix(in oklab,var(--muted) 40%,transparent)',
    borderBlockStyle: 'solid',
    borderBlockWidth: 1,
    borderBlockColor: 'var(--border)',
  },
  columns: {
    marginInline: 'auto',
    display: 'grid',
    width: '100%',
    maxWidth: '1200px',
    alignItems: 'start',
    gap: '2.5rem',
    paddingInline: { default: '1rem', '@media (min-width: 768px)': '2rem' },
    paddingBlock: '4rem',
    gridTemplateColumns: {
      default: 'minmax(0,1fr)',
      '@media (min-width: 768px)': 'repeat(2,minmax(0,1fr))',
    },
  },
  stack: { display: 'flex', flexDirection: 'column', gap: '1.5rem' },
  grid: { display: 'grid', gap: '.5rem' },
  stackTight: { display: 'flex', flexDirection: 'column', gap: '1rem' },
  installCard: {
    backgroundColor: 'var(--background)',
    display: 'flex',
    flexDirection: 'column',
    gap: '.75rem',
    borderRadius: '.75rem',
    borderStyle: 'solid',
    borderWidth: 1,
    borderColor: 'var(--border)',
    padding: '1rem',
    minWidth: 0,
  },
  installRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '.5rem',
    flexWrap: 'wrap',
  },
  code: {
    fontFamily:
      'var(--font-mono, ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace)',
    fontSize: '.875rem',
    lineHeight: '1.25rem',
    overflowWrap: 'anywhere',
  },
  checks: {
    color: 'var(--muted-foreground)',
    display: 'grid',
    gap: '.5rem',
    fontSize: '.875rem',
    lineHeight: '1.25rem',
    listStyleType: 'none',
  },
  check: { display: 'flex', alignItems: 'center', gap: '.5rem' },
  stat: {
    backgroundColor: {
      default: 'transparent',
      ':hover': 'color-mix(in oklab,var(--muted) 50%,transparent)',
    },
    display: 'flex',
    flexDirection: 'column',
    gap: '.25rem',
    borderRadius: '.75rem',
    borderStyle: 'solid',
    borderWidth: 1,
    borderColor: 'var(--border)',
    padding: '1.5rem',
    transitionProperty: 'background-color',
    transitionDuration: '.15s',
  },
  statValue: {
    fontSize: '1.875rem',
    lineHeight: '2.25rem',
    fontWeight: 600,
    letterSpacing: '-.025em',
  },
  stats: {
    display: 'grid',
    gap: '1rem',
    gridTemplateColumns: {
      default: 'minmax(0,1fr)',
      '@media (min-width: 640px)': 'repeat(3,minmax(0,1fr))',
    },
  },
  snippet: {
    backgroundColor: 'var(--background)',
    overflowX: 'auto',
    borderRadius: '.75rem',
    borderStyle: 'solid',
    borderWidth: 1,
    borderColor: 'var(--border)',
    padding: '1rem',
    fontFamily:
      'var(--font-mono, ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace)',
    fontSize: '.75rem',
    lineHeight: 1.625,
  },
  faqItem: { display: 'flex', flexDirection: 'column', gap: '.375rem' },
  faqGrid: {
    display: 'grid',
    gap: '2rem',
    gridTemplateColumns: {
      default: 'minmax(0,1fr)',
      '@media (min-width: 768px)': 'repeat(2,minmax(0,1fr))',
    },
  },
  footer: { borderTop: '1px solid var(--border)' },
  footerInner: {
    color: 'var(--muted-foreground)',
    marginInline: 'auto',
    display: 'flex',
    width: '100%',
    maxWidth: '1200px',
    flexWrap: 'wrap',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '1rem',
    paddingInline: { default: '1rem', '@media (min-width: 768px)': '2rem' },
    paddingBlock: '2.5rem',
    fontSize: '.875rem',
    lineHeight: '1.25rem',
  },
  footerLinks: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: '1rem',
  },
  footerLink: { color: { default: 'inherit', ':hover': 'var(--foreground)' } },
  revision: {
    fontFamily:
      'var(--font-mono, ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace)',
    color: { default: 'inherit', ':hover': 'var(--foreground)' },
  },
  icon: { width: '1rem', height: '1rem' },
})

// These defaults apply only to this template's own elements. Child component
// previews receive their own resets, exactly as they do in a consumer app.
export const landingSkin = Object.fromEntries(
  Object.entries(styles).map(([key, style]) => [
    key,
    className(reset.text, reset.link, style),
  ]),
) as Record<keyof typeof styles, string>
