import type { skin as tailwindSkin } from './skin'
import * as stylex from '@stylexjs/stylex'
import { reset } from '@/stylex/reset'
import { className } from '@/stylex/style'
import { tokens } from '../stylex/tokens.stylex'
import { interactionTokens } from '../stylex/interaction-tokens.stylex.const'

const styles = stylex.create({
  header: {
    position: 'sticky',
    top: 0,
    zIndex: 40,
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
    borderBottomColor: tokens.border,
    backgroundColor: tokens.background,
  },
  bar: {
    marginInline: 'auto',
    display: 'flex',
    minHeight: '3.5rem',
    width: '100%',
    maxWidth: '1400px',
    alignItems: 'center',
    gap: { default: '1rem', '@media (min-width: 768px)': '1.5rem' },
    paddingInline: { default: '1rem', '@media (min-width: 768px)': '2rem' },
  },
  brand: {
    flexShrink: 0,
    fontSize: '.875rem',
    lineHeight: '1.25rem',
    fontWeight: 600,
  },
  nav: {
    display: { default: 'none', '@media (min-width: 640px)': 'flex' },
    alignItems: 'center',
    gap: '1.5rem',
  },
  link: {
    fontSize: '.875rem',
    lineHeight: '1.25rem',
    fontWeight: 500,
    color: { default: tokens.mutedForeground, ':hover': tokens.foreground },
    transitionProperty: 'color',
    transitionDuration: '.15s',
  },
  active: {
    fontSize: '.875rem',
    lineHeight: '1.25rem',
    fontWeight: 500,
    color: tokens.foreground,
    transitionProperty: 'color',
    transitionDuration: '.15s',
  },
  other: {
    fontSize: '.75rem',
    lineHeight: '1rem',
    fontWeight: 500,
    color: { default: tokens.mutedForeground, ':hover': tokens.foreground },
  },
  actions: {
    marginLeft: 'auto',
    display: 'flex',
    alignItems: 'center',
    gap: { default: '.25rem', '@media (min-width: 640px)': '.5rem' },
  },
  searchTrigger: {
    display: 'inline-flex',
    width: { default: '2.5rem', '@media (min-width: 1024px)': '15rem' },
    height: { default: '2.5rem', '@media (min-width: 1024px)': '2.25rem' },
    flexShrink: 0,
    cursor: interactionTokens.cursorAction,
    alignItems: 'center',
    justifyContent: {
      default: 'center',
      '@media (min-width: 1024px)': 'flex-start',
    },
    gap: '.5rem',
    borderRadius: tokens.controlRadius,
    borderStyle: 'solid',
    borderWidth: 1,
    borderColor: tokens.border,
    backgroundColor: {
      default: 'color-mix(in oklab, var(--muted) 30%, transparent)',
      ':hover': 'color-mix(in oklab, var(--muted) 60%, transparent)',
    },
    color: { default: tokens.mutedForeground, ':hover': tokens.foreground },
    fontSize: '.875rem',
    lineHeight: '1.25rem',
    outlineStyle: 'none',
    boxShadow: {
      default: tokens.shadowNone,
      ':focus-visible': tokens.focusRingOffsetShadow,
    },
    paddingInline: { default: 0, '@media (min-width: 1024px)': '.75rem' },
    transitionProperty: 'color, background-color',
    transitionDuration: {
      default: interactionTokens.motionFast,
      '@media (prefers-reduced-motion: reduce)': interactionTokens.motionNone,
    },
  },
  searchLabel: {
    display: { default: 'none', '@media (min-width: 1024px)': 'inline' },
  },
  searchShortcut: {
    marginLeft: 'auto',
    display: { default: 'none', '@media (min-width: 1024px)': 'inline-flex' },
    borderRadius: '.25rem',
    border: '1px solid var(--border)',
    backgroundColor: tokens.background,
    paddingInline: '.25rem',
    fontFamily: 'inherit',
    fontSize: '10px',
    fontWeight: 500,
    lineHeight: '1.25rem',
  },
  searchResults: { minWidth: 0 },
  searchResult: {
    display: 'flex',
    width: '100%',
    minWidth: 0,
    alignItems: 'center',
    gap: '.75rem',
    paddingBlock: '.25rem',
  },
  searchResultIcon: {
    width: '1rem',
    height: '1rem',
    flexShrink: 0,
    color: tokens.mutedForeground,
  },
  searchResultCopy: {
    display: 'flex',
    minWidth: 0,
    flex: '1',
    flexDirection: 'column',
    gap: '.25rem',
  },
  searchResultTitle: {
    fontSize: '.875rem',
    lineHeight: '1.25rem',
    fontWeight: 500,
  },
  searchResultDescription: {
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    fontSize: '.75rem',
    lineHeight: '1rem',
    color: 'color-mix(in oklab, var(--foreground) 75%, transparent)',
  },
  searchHelp: {
    display: 'flex',
    width: '100%',
    flexWrap: 'wrap',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '.75rem',
    borderTop: '1px solid var(--border)',
    paddingTop: '.75rem',
    fontSize: '.75rem',
    lineHeight: '1rem',
    color: tokens.mutedForeground,
  },
  theme: {
    display: 'inline-flex',
    width: '2.5rem',
    height: '2.5rem',
    flexShrink: 0,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '.375rem',
    cursor: 'pointer',
    color: { default: tokens.foreground, ':hover': tokens.accentForeground },
    backgroundColor: { default: tokens.transparent, ':hover': tokens.accent },
    boxShadow: { default: 'none', ':focus-visible': tokens.focusRingShadow },
    transform: { default: 'scale(1)', ':active': 'scale(0.96)' },
    transitionProperty: 'color, background-color, transform',
    transitionDuration: '.2s',
  },
  themeIconWrap: {
    position: 'relative',
    width: '1rem',
    height: '1rem',
  },
  mobile: {
    position: 'relative',
    display: { default: 'block', '@media (min-width: 640px)': 'none' },
  },
  summary: {
    display: 'flex',
    width: '2.5rem',
    height: '2.5rem',
    cursor: 'pointer',
    listStyleType: 'none',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '.375rem',
    backgroundColor: { default: tokens.transparent, ':hover': tokens.accent },
  },
  menu: {
    position: 'absolute',
    top: '2.75rem',
    right: 0,
    zIndex: 50,
    display: 'grid',
    minWidth: '11rem',
    gap: '1rem',
    borderRadius: '.5rem',
    borderStyle: 'solid',
    borderWidth: 1,
    borderColor: tokens.border,
    backgroundColor: tokens.background,
    padding: '1rem',
  },
  icon: { width: '1rem', height: '1rem' },
  notFound: {
    marginInline: 'auto',
    maxWidth: '36rem',
    paddingInline: '2rem',
    paddingBlock: '4rem',
    color: tokens.mutedForeground,
  },
})

export const skin = {
  header: className(styles.header),
  bar: className(styles.bar),
  brand: className(reset.link, styles.brand),
  nav: className(styles.nav),
  link: className(reset.link, styles.link),
  active: className(reset.link, styles.link, styles.active),
  other: className(reset.link, styles.other),
  actions: className(styles.actions),
  searchTrigger: className(reset.button, styles.searchTrigger),
  searchLabel: className(styles.searchLabel),
  searchShortcut: className(reset.text, styles.searchShortcut),
  searchResults: className(styles.searchResults),
  searchResult: className(styles.searchResult),
  searchResultIcon: className(styles.searchResultIcon),
  searchResultCopy: className(styles.searchResultCopy),
  searchResultTitle: className(styles.searchResultTitle),
  searchResultDescription: className(styles.searchResultDescription),
  searchHelp: className(styles.searchHelp),
  theme: className(reset.button, styles.theme),
  iconLink: className(reset.link, styles.theme),
  themeIconWrap: className(styles.themeIconWrap),
  themeIconSun: 'theme-toggle-icon theme-toggle-icon-sun',
  themeIconMoon: 'theme-toggle-icon theme-toggle-icon-moon',
  mobile: className(styles.mobile),
  summary: className(styles.summary),
  menu: className(styles.menu),
  icon: className(styles.icon),
  notFound: className(reset.text, styles.notFound),
} satisfies Record<keyof typeof tailwindSkin, string>
