import * as Textarea from '@/ui/textarea';
import { authoredPage, controlledTextApplication, textPreviewProgram } from '@/docs/components/pages/authored-page';

const previewProgram = textPreviewProgram('textarea', ['', 'Too short', 'This value is generated by the build.', 'First line\nSecond line'], (index, value, onInput, h) => {
  const control = Textarea.textarea({ id: `docs-textarea-${String(index)}`, value, onInput, class: 'max-w-md', label: index === 0 ? 'Message' : index === 1 ? 'Release notes' : index === 2 ? 'Generated summary' : 'Deployment notes', ...(index === 0 ? { description: 'Include enough context for the reviewer.', placeholder: 'Describe the change…', rows: 4 } : {}), ...(index === 1 ? { description: 'Release notes must contain at least 20 characters.', isInvalid: true } : {}), ...(index === 2 ? { isDisabled: true } : {}), ...(index === 3 ? { name: 'notes', form: 'textarea-profile', rows: 5, wrap: 'hard' as const, resize: 'none' as const, isReadOnly: true } : {}) }, h);
  return index === 3 ? h.div([], [h.form([h.Id('textarea-profile')], []), control]) : control;
});

const source = (name: string, initialValue: string, config: string): string => controlledTextApplication({
  componentName: 'Textarea', componentSlug: 'textarea', exampleName: name, field: 'message', initialValue,
  viewBody: `Textarea.textarea({
  id: 'message',
  value: model.message,
  onInput: value => ChangedTextarea({ value }),
  ${config}
}, h),`,
});

export const textareaPage = authoredPage({
  slug: 'textarea', title: 'Textarea', kind: 'helper',
  previewProgram,
  definition: {
    kind: 'helper', description: 'Captures controlled multi-line text with accessible labeling and validation.',
    architecture: 'Textarea is a stateless controlled helper with no child Model. The parent owns its text, validation, and submission policy; rows, wrapping, labels, descriptions, and resize policy are per-render inputs. Both skins share one semantic renderer and reflect parent changes directly.',
    apiHref: 'https://foldkit.dev/ui/textarea',
    styling: 'Set rows for an initial height and allow field-sizing to grow with content. Use class to constrain the surrounding layout.',
    accessibility: 'Use a visible label and linked correction guidance. Description IDs are deterministic and emitted only with real description content. Native disabled, read-only, invalid, form, rows, wrapping, and naming behavior is preserved.',
    examples: [
      {
        title: 'Message', description: 'Keep multi-line content in the parent Model like any other controlled value.',

        code: source('Message', '', `label: 'Message',
  description: 'Include enough context for the reviewer.',
  placeholder: 'Describe the change…',
  rows: 4,`),
      },
      {
        title: 'Invalid', description: 'Pair invalid state with specific correction guidance.',

        code: source('Invalid', 'Too short', `label: 'Release notes',
  description: 'Release notes must contain at least 20 characters.',
  isInvalid: true,`),
      },
      {
        title: 'Disabled', description: 'Disabled state prevents editing without discarding controlled text.',

        code: source('Disabled', 'This value is generated by the build.', `label: 'Generated summary',
  isDisabled: true,`),
      },
      {
        title: 'Form and resize', description: 'Associate multiline content with a native form and select one finite resize policy without changing value ownership.',

        code: source('Form and resize', 'First line\nSecond line', `label: 'Deployment notes',
  name: 'notes',
  form: 'textarea-profile',
  rows: 5,
  wrap: 'hard',
  resize: 'none',
  isReadOnly: true,`),
      },
    ],
  },
});
