import * as Textarea from '@/ui/textarea';
import * as State from '@/docs/components/catalog-state';
import { authoredPage, controlledTextApplication } from '@/docs/components/pages/authored-page';

const source = (name: string, initialValue: string, config: string): string => controlledTextApplication({
  componentName: 'Textarea', componentSlug: 'textarea', exampleName: name, field: 'message', initialValue,
  viewBody: `Textarea.textarea({
  id: 'message',
  value: model.message,
  onInput: value => ChangedTextarea({ value }),
  ${config}
}, h),`,
});

export const textareaPage = authoredPage({
  slug: 'textarea', title: 'Textarea', kind: 'helper',
  definition: {
    kind: 'helper', description: 'Captures controlled multi-line text with accessible labeling and validation.',
    architecture: 'Textarea is a stateless controlled helper. The application Model owns its text and onInput returns a typed change Message.',
    apiHref: 'https://foldkit.dev/ui/textarea',
    styling: 'Set rows for an initial height and allow field-sizing to grow with content. Use class to constrain the surrounding layout.',
    accessibility: 'Use a visible label and a linked description for requirements or correction guidance. isInvalid communicates semantic error state.',
    examples: [
      {
        title: 'Message', description: 'Keep multi-line content in the parent Model like any other controlled value.',
        preview: (model, h) => Textarea.textarea({ id: 'docs-textarea-message', label: 'Message', description: 'Include enough context for the reviewer.', value: model.textarea, onInput: (value) => State.ChangedText({ target: 'textarea', value }), placeholder: 'Describe the change…', rows: 4, class: 'max-w-md' }, h),
        code: source('Message', '', `label: 'Message',
  description: 'Include enough context for the reviewer.',
  placeholder: 'Describe the change…',
  rows: 4,`),
      },
      {
        title: 'Invalid', description: 'Pair invalid state with specific correction guidance.',
        preview: (model, h) => Textarea.textarea({ id: 'docs-textarea-invalid', label: 'Release notes', description: 'Release notes must contain at least 20 characters.', value: model.textarea, onInput: (value) => State.ChangedText({ target: 'textarea', value }), isInvalid: true, class: 'max-w-md' }, h),
        code: source('Invalid', 'Too short', `label: 'Release notes',
  description: 'Release notes must contain at least 20 characters.',
  isInvalid: true,`),
      },
      {
        title: 'Disabled', description: 'Disabled state prevents editing without discarding controlled text.',
        preview: (_model, h) => Textarea.textarea({ id: 'docs-textarea-disabled', label: 'Generated summary', value: 'This value is generated by the build.', onInput: (value) => State.ChangedText({ target: 'textarea', value }), isDisabled: true, class: 'max-w-md' }, h),
        code: source('Disabled', 'This value is generated by the build.', `label: 'Generated summary',
  isDisabled: true,`),
      },
    ],
  },
});
